//! `BlobStore` trait + companion types for original-bytes preservation.
//!
//! Spec: `docs/design/phase2/11-raw-ingestion-and-rag.md` §4.3 (core trait
//! surface) and §5.1 (`ingested_blobs` schema — the Postgres migration lands
//! in W3-KL-3 alongside `FilesystemBlobStore`).
//!
//! # Scope for W3-KL-2
//!
//! Only the trait shape + wire types land here. The pipeline in W3-KL-2
//! computes `content_hash` directly via `sha256(bytes)` without writing to a
//! blob store — enough for citation-hash frontmatter, not yet enough for
//! dedup / redownload / blob viewer. `FilesystemBlobStore` + the `BlobRef`
//! existed-flag dedup logic come in W3-KL-3.
//!
//! # Error taxonomy
//!
//! [`BlobError`] is `non_exhaustive` so adding (e.g.) `AccessDenied` in the
//! S3-impl PR is additive. `sha256:` prefix is enforced by convention; the
//! actual `CHECK (content_hash ~ '^sha256:[0-9a-f]{64}$')` invariant lives
//! in the database migration.

use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Opaque blob identifier. UUID v4 generated by the store on `put`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct BlobId(pub Uuid);

impl BlobId {
    /// Mint a fresh blob id. Used by in-memory / filesystem store impls;
    /// future S3 impl may defer id generation to the upload-id flow.
    pub fn new_v4() -> Self {
        Self(Uuid::new_v4())
    }
}

impl std::fmt::Display for BlobId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}

/// Caller-supplied metadata accompanying a blob upload.
///
/// Per design 11 §5.1, the persisted `ingested_blobs` row carries tenant +
/// hash + filename + importer. The `tenant_id` / `user_id` references resolve
/// to `String` here because the identity module (08 doc) owns the typed
/// newtypes — pulling those into core would create a cycle.
#[derive(Debug, Clone)]
pub struct BlobMetadata {
    pub tenant_id: String,
    pub content_type: String,
    pub filename: String,
    pub byte_size: u64,
    pub imported_by: String,
}

/// Handle returned from [`BlobStore::put`].
///
/// `existed` is the dedup signal: the store hashed the bytes, saw a
/// matching row in `ingested_blobs` (same `(tenant_id, content_hash)`),
/// and short-circuited the write. Pipelines surface this in the import
/// receipt as `blob_existed`.
#[derive(Debug, Clone)]
pub struct BlobRef {
    pub id: BlobId,
    /// SHA-256 hex digest prefixed with `"sha256:"`. Guaranteed format by
    /// store impls (filesystem computes locally; DB CHECK constraint
    /// catches malformed writes).
    pub content_hash: String,
    /// Transport URI (`file://...` | `s3://...`). Opaque to the knowledge
    /// layer; used by the future blob-viewer endpoint.
    pub storage_uri: String,
    pub byte_size: u64,
    /// `true` = dedup hit (bytes already present); `false` = fresh insert.
    pub existed: bool,
}

/// Pluggable original-bytes store.
///
/// Registration surface (future W3-KL-3):
/// `ctx.plugs.blob_stores.register(PlugId::new("filesystem-blob")?, ...)`.
/// The current W3-KL-2 pipeline keeps the trait in `gadgetron-core` so the
/// axis can land in `PlugHandles` ahead of the first impl — mirrors the
/// pattern used for `LlmProvider` in W2.
#[async_trait::async_trait]
pub trait BlobStore: Send + Sync + std::fmt::Debug {
    /// Persist `bytes` + `meta`. If a row with the same
    /// `(meta.tenant_id, sha256(bytes))` already exists, return the
    /// existing `BlobRef` with `existed = true`. Otherwise insert and
    /// return with `existed = false`.
    async fn put(&self, bytes: &[u8], meta: &BlobMetadata) -> Result<BlobRef, BlobError>;

    /// Fetch bytes by id. Returned as an owned `Vec<u8>` so the trait
    /// stays in `gadgetron-core` without pulling the `bytes` crate into
    /// the leaf-core dependency set (D-12 leaf). Implementations that
    /// need zero-copy semantics can expose additional inherent methods.
    async fn get(&self, id: &BlobId) -> Result<Vec<u8>, BlobError>;

    /// Remove the blob. Callers verify no live `wiki_pages` row references
    /// the id before calling this (`blob.gc_reclaimed` audit event).
    async fn delete(&self, id: &BlobId) -> Result<(), BlobError>;

    /// Cheap existence check. Useful for the future blob-viewer endpoint
    /// which wants to 404 fast without paying the fetch cost.
    async fn exists(&self, id: &BlobId) -> Result<bool, BlobError>;
}

/// Failures from [`BlobStore`] operations. `non_exhaustive` so additive
/// variants (`AccessDenied`, `ChecksumMismatch`) stay non-breaking.
#[non_exhaustive]
#[derive(thiserror::Error, Debug)]
pub enum BlobError {
    #[error("blob not found: {0:?}")]
    NotFound(BlobId),
    #[error("storage unavailable: {0}")]
    StorageUnavailable(String),
    #[error("size limit exceeded: {size} > {limit}")]
    TooLarge { size: u64, limit: u64 },
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
    #[error("database error: {0}")]
    Database(String),
}

impl BlobError {
    /// Stable snake_case code matching [`crate::ingest::ExtractError::code`]
    /// style; audit pipelines surface this without interpolation.
    pub fn code(&self) -> &'static str {
        match self {
            Self::NotFound(_) => "blob_not_found",
            Self::StorageUnavailable(_) => "blob_storage_unavailable",
            Self::TooLarge { .. } => "blob_too_large",
            Self::Io(_) => "blob_io",
            Self::Database(_) => "blob_database",
        }
    }
}
