use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    net::IpAddr,
    path::Path,
    process::Stdio,
    time::Duration,
};

use gadgetron_bundle_sdk::{LocalId, TargetSetupFeature};
use serde::{Deserialize, Serialize};
use tokio::{
    io::{AsyncRead, AsyncReadExt, AsyncWriteExt},
    process::Command,
    time::timeout,
};
use uuid::Uuid;
use zeroize::Zeroize;

use super::{
    host_key_alias, known_hosts_path, require_secure_regular_file, resolve_address,
    secret_key_path, secure_directory, validate_host_key, validate_label, validate_username,
    write_known_hosts, BundleSshControlPlane, BundleSshError, BundleSshTarget,
    PutBundleSshSecretRequest, PutBundleSshTargetRequest, RecordKey, SshAddressPolicy,
    SshCredentialOrigin, SshHopConfig, SshTargetLifecycleState,
};

const SSH_PASS_PATH: &str = "/usr/bin/sshpass";
const BOOTSTRAP_CONNECT_TIMEOUT: Duration = Duration::from_secs(20);
const BOOTSTRAP_SETUP_TIMEOUT: Duration = Duration::from_secs(15 * 60);
const BOOTSTRAP_OUTPUT_LIMIT: usize = 64 * 1024;
const SECRET_RESOURCE: &str = "secret:use:ssh-identity";

/// One-shot registration request. Password fields are deliberately neither
/// `Debug` nor `Serialize` and are wiped when the request leaves scope.
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BootstrapBundleSshTargetRequest {
    pub address: String,
    pub username: String,
    pub password: String,
    #[serde(default)]
    pub sudo_password: Option<String>,
    #[serde(default = "super::default_ssh_port")]
    pub port: u16,
    #[serde(default)]
    pub label: Option<String>,
    #[serde(default)]
    pub target_profile_id: Option<String>,
    #[serde(default)]
    pub parameters: BTreeMap<String, serde_json::Value>,
    #[serde(default)]
    pub setup_features: Option<Vec<TargetSetupFeature>>,
    #[serde(default = "default_bootstrap_address_policy")]
    pub address_policy: SshAddressPolicy,
    #[serde(default)]
    pub acting_space_id: Option<Uuid>,
    #[serde(skip)]
    registered_by_user_id: Option<Uuid>,
}

impl BootstrapBundleSshTargetRequest {
    pub fn bind_registration_actor(&mut self, user_id: Uuid) {
        self.registered_by_user_id = Some(user_id);
    }
}

#[derive(Debug, Clone)]
pub struct BootstrapSshTargetProfile {
    pub id: LocalId,
    pub allowed_operations: Vec<String>,
    pub setup_features: Vec<TargetSetupFeature>,
    pub route_parent_target_id: Option<LocalId>,
}

impl Drop for BootstrapBundleSshTargetRequest {
    fn drop(&mut self) {
        self.password.zeroize();
        if let Some(password) = &mut self.sudo_password {
            password.zeroize();
        }
    }
}

#[derive(Debug, Clone, Serialize)]
pub struct BootstrapStage {
    pub id: &'static str,
    pub status: &'static str,
    pub detail: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct BootstrapBundleSshTargetResponse {
    pub target: BundleSshTarget,
    pub os_family: String,
    pub installed_packages: Vec<String>,
    pub skipped_packages: Vec<String>,
    pub stages: Vec<BootstrapStage>,
    pub first_collection_verified: bool,
}

/// One-shot credential request for an existing target. The credential is
/// consumed only by the Core-owned setup process and is wiped on drop.
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ReapplyBundleSshTargetSetupRequest {
    pub expected_target_revision: String,
    pub sudo_password: String,
    pub setup_features: Vec<TargetSetupFeature>,
    #[serde(default)]
    pub parameters: BTreeMap<String, serde_json::Value>,
}

impl Drop for ReapplyBundleSshTargetSetupRequest {
    fn drop(&mut self) {
        self.sudo_password.zeroize();
    }
}

#[derive(Debug, Clone, Serialize)]
pub struct ReapplyBundleSshTargetSetupResponse {
    pub target_id: String,
    pub target_revision: String,
    pub target_profile_id: String,
    pub os_family: String,
    pub setup_features: Vec<TargetSetupFeature>,
    pub installed_packages: Vec<String>,
    pub skipped_packages: Vec<String>,
    pub stages: Vec<BootstrapStage>,
}

#[derive(Debug)]
struct CommandOutput {
    stdout: String,
    stderr: String,
    success: bool,
}

#[derive(Clone)]
struct BootstrapSshConnection {
    username: String,
    ip: IpAddr,
    port: u16,
    alias: String,
    known_hosts_path: std::path::PathBuf,
    private_key_path: Option<std::path::PathBuf>,
    route_parent: Option<SshHopConfig>,
}

impl BundleSshControlPlane {
    /// Removes only keys generated by the simple bootstrap flow. Advanced
    /// credentials may be shared or operator-owned and are never touched.
    pub async fn remove_bootstrap_authorization(
        &self,
        tenant_id: Uuid,
        bundle_id: &str,
        target_id: &str,
    ) -> Result<bool, BundleSshError> {
        let key = RecordKey::new(tenant_id, bundle_id, target_id);
        let target = self
            .inner
            .targets
            .read()
            .expect("Core SSH target lock poisoned")
            .get(&key)
            .cloned()
            .ok_or(BundleSshError::TargetNotFound)?;
        if target.credential_origin != SshCredentialOrigin::Bootstrap {
            return Ok(false);
        }
        let secret_key = RecordKey::new(tenant_id, bundle_id, &target.secret_id);
        let private_key_path = secret_key_path(&self.inner.secrets_root, &secret_key);
        require_secure_regular_file(&private_key_path).map_err(|_| BundleSshError::Persistence)?;
        let ips = resolve_address(&target.address, target.port, target.address_policy).await?;
        let ip = *ips.first().ok_or(BundleSshError::DependencyUnavailable)?;
        let alias = host_key_alias(&key);
        let host_keys = known_hosts_path(&self.inner.known_hosts_root, &key);
        write_known_hosts(&host_keys, &alias, &target.host_key)
            .map_err(|_| BundleSshError::Persistence)?;
        let connection = BootstrapSshConnection {
            username: target.username,
            ip,
            port: target.port,
            alias,
            known_hosts_path: host_keys,
            private_key_path: Some(private_key_path),
            route_parent: match target.route_parent_target_id.as_deref() {
                Some(parent_id) => {
                    let parent_id = LocalId::new(parent_id.to_string())
                        .map_err(|error| BundleSshError::Invalid(error.to_string()))?;
                    let parent = self.active_direct_target(tenant_id, bundle_id, &parent_id)?;
                    Some(self.prepare_ssh_hop(&parent).await?)
                }
                None => None,
            },
        };
        self.remove_remote_bootstrap_key(&connection, target_id)
            .await?;
        Ok(true)
    }

    pub async fn bootstrap_target(
        &self,
        tenant_id: Uuid,
        bundle_id: &str,
        target_id: &LocalId,
        profile: BootstrapSshTargetProfile,
        mut request: BootstrapBundleSshTargetRequest,
    ) -> Result<BootstrapBundleSshTargetResponse, BundleSshError> {
        validate_username(&request.username)?;
        if request.port == 0 {
            return Err(BundleSshError::Invalid("SSH port must be non-zero".into()));
        }
        if request.password.is_empty() || request.password.len() > 4_096 {
            return Err(BundleSshError::Invalid(
                "SSH bootstrap password must be between 1 and 4096 bytes".into(),
            ));
        }
        let label = request
            .label
            .as_deref()
            .map(str::trim)
            .filter(|value| !value.is_empty())
            .unwrap_or(&request.address)
            .to_string();
        validate_label(&label)?;
        if profile.allowed_operations.is_empty() {
            return Err(BundleSshError::Invalid(
                "signed Bundle package declares no SSH monitoring operations".into(),
            ));
        }
        if !self.inner.ssh_path.is_file()
            || !self.inner.ssh_keygen_path.is_file()
            || !Path::new(SSH_PASS_PATH).is_file()
        {
            return Err(BundleSshError::DependencyUnavailable);
        }

        let ips = resolve_address(&request.address, request.port, request.address_policy).await?;
        let ip = *ips.first().ok_or(BundleSshError::DependencyUnavailable)?;
        let route_parent = match profile.route_parent_target_id.as_ref() {
            Some(parent_id) => {
                if request.address.parse::<IpAddr>().is_err() || ips.len() != 1 {
                    return Err(BundleSshError::Invalid(
                        "routed SSH child address must be one canonical IP literal".into(),
                    ));
                }
                let parent = self.active_direct_target(tenant_id, bundle_id, parent_id)?;
                Some(self.prepare_ssh_hop(&parent).await?)
            }
            None => None,
        };
        let record_key = RecordKey::new(tenant_id, bundle_id, target_id.as_str());
        let alias = host_key_alias(&record_key);
        let staging = self
            .inner
            .secrets_root
            .join(format!(".bootstrap-{}", Uuid::new_v4()));
        fs::create_dir(&staging).map_err(|_| BundleSshError::Persistence)?;
        secure_directory(&staging).map_err(|_| BundleSshError::Persistence)?;
        let _staging = StagingDirectory(staging.clone());
        let private_key_path = staging.join("identity");
        let known_hosts_path = staging.join("known_hosts");
        let mut stages = Vec::new();
        let password_connection = BootstrapSshConnection {
            username: request.username.clone(),
            ip,
            port: request.port,
            alias: alias.clone(),
            known_hosts_path: known_hosts_path.clone(),
            private_key_path: None,
            route_parent,
        };

        let probe = self
            .run_password_command(
                &password_connection,
                &request.password,
                "printf '__gadgetron_password_ready__\\n'; hostname 2>/dev/null || uname -n",
                None,
                BOOTSTRAP_CONNECT_TIMEOUT,
            )
            .await?;
        require_marker(&probe, "authenticate", "__gadgetron_password_ready__")?;
        let remote_hostname = probe
            .stdout
            .lines()
            .find(|line| !line.starts_with("__gadgetron_"))
            .map(str::trim)
            .filter(|line| !line.is_empty())
            .unwrap_or(&label)
            .to_string();
        stages.push(stage(
            "authenticate",
            format!("Authenticated as {}", request.username),
        ));

        self.generate_bootstrap_key(&private_key_path, target_id.as_str())
            .await?;
        let key_connection = BootstrapSshConnection {
            private_key_path: Some(private_key_path.clone()),
            ..password_connection.clone()
        };
        let public_key = fs::read_to_string(private_key_path.with_extension("pub"))
            .map_err(|_| bootstrap_error("generate-key", "generated public key is unavailable"))?;
        let public_key = public_key.trim();
        let install_command = install_public_key_command(public_key, target_id.as_str());
        let install = self
            .run_password_command(
                &password_connection,
                &request.password,
                &install_command,
                None,
                BOOTSTRAP_CONNECT_TIMEOUT,
            )
            .await?;
        if let Err(error) = require_marker(&install, "install-key", "__gadgetron_key_installed__") {
            let rollback = self
                .remove_remote_bootstrap_key(&key_connection, target_id.as_str())
                .await;
            return Err(attach_rollback_result(error, rollback));
        }
        stages.push(stage(
            "install-key",
            "Installed a target-specific ed25519 key",
        ));

        let completion = async {
            let os_probe = self
                .run_key_command(
                    &key_connection,
                    os_probe_command(),
                    None,
                    BOOTSTRAP_CONNECT_TIMEOUT,
                )
                .await?;
            require_marker(&os_probe, "detect-os", "__gadgetron_key_ready__")?;
            let os_family = parse_os_family(&os_probe.stdout).to_string();
            if os_family == "unknown" {
                return Err(bootstrap_error(
                    "detect-os",
                    "automatic monitoring setup supports Debian- and RHEL-family Linux",
                ));
            }
            stages.push(stage("detect-os", format!("Detected {os_family}")));

            let sudo_password = request
                .sudo_password
                .as_deref()
                .filter(|value| !value.is_empty())
                .unwrap_or(&request.password);
            let setup_command =
                setup_command(&os_family, &request.username, &profile.setup_features);
            let setup = self
                .run_key_command(
                    &key_connection,
                    &setup_command,
                    Some(sudo_password.as_bytes()),
                    BOOTSTRAP_SETUP_TIMEOUT,
                )
                .await?;
            require_marker(&setup, "install-software", "__gadgetron_setup_ready__")?;
            let (installed_packages, skipped_packages) = parse_package_report(&setup.stdout);
            stages.push(stage(
                "install-software",
                format!(
                    "Installed {} monitoring packages; {} unavailable",
                    installed_packages.len(),
                    skipped_packages.len()
                ),
            ));

            let feature_verify = verify_command(&profile.setup_features);
            let verify = self
                .run_key_command(
                    &key_connection,
                    &feature_verify,
                    None,
                    BOOTSTRAP_CONNECT_TIMEOUT,
                )
                .await?;
            require_marker(&verify, "verify-key", "__gadgetron_verify_ready__")?;
            stages.push(stage("verify-key", "Verified passwordless key-only SSH"));

            let host_key = read_captured_host_key(&known_hosts_path, &alias)?;
            let private_key = fs::read_to_string(&private_key_path)
                .map_err(|_| bootstrap_error("persist", "generated private key is unavailable"))?;
            self.put_secret(
                tenant_id,
                bundle_id,
                target_id.as_str(),
                PutBundleSshSecretRequest {
                    resource: SECRET_RESOURCE.into(),
                    private_key,
                },
            )
            .await?;
            let target_result = self
                .put_target_with_state(
                    tenant_id,
                    bundle_id,
                    target_id.as_str(),
                    PutBundleSshTargetRequest {
                        label: request
                            .label
                            .take()
                            .filter(|value| !value.trim().is_empty())
                            .unwrap_or(remote_hostname),
                        address: request.address.clone(),
                        port: request.port,
                        username: request.username.clone(),
                        host_key_algorithm: host_key.0,
                        host_public_key_base64: host_key.1,
                        secret_id: target_id.to_string(),
                        secret_resource: SECRET_RESOURCE.into(),
                        allowed_operations: profile.allowed_operations,
                        target_profile_id: Some(profile.id.into_inner()),
                        route_parent_target_id: profile
                            .route_parent_target_id
                            .map(LocalId::into_inner),
                        address_policy: request.address_policy,
                        acting_space_id: request.acting_space_id,
                        registered_by_user_id: request.registered_by_user_id,
                    },
                    SshTargetLifecycleState::Provisioning,
                    SshCredentialOrigin::Bootstrap,
                )
                .await;
            let target = match target_result {
                Ok(target) => target,
                Err(error) => {
                    let _ = self
                        .delete_secret(tenant_id, bundle_id, target_id.as_str())
                        .await;
                    return Err(error);
                }
            };
            stages.push(stage(
                "persist",
                format!("Pinned host key {}", target.host_key.fingerprint),
            ));

            Ok(BootstrapBundleSshTargetResponse {
                target,
                os_family,
                installed_packages,
                skipped_packages,
                stages,
                first_collection_verified: false,
            })
        }
        .await;
        match completion {
            Ok(response) => Ok(response),
            Err(error) => {
                let rollback = self
                    .remove_remote_bootstrap_key(&key_connection, target_id.as_str())
                    .await;
                Err(attach_rollback_result(error, rollback))
            }
        }
    }

    pub async fn reapply_target_setup(
        &self,
        tenant_id: Uuid,
        bundle_id: &str,
        target_id: &str,
        mut request: ReapplyBundleSshTargetSetupRequest,
    ) -> Result<ReapplyBundleSshTargetSetupResponse, BundleSshError> {
        if request.sudo_password.is_empty() || request.sudo_password.len() > 4_096 {
            return Err(BundleSshError::Invalid(
                "SSH setup credential must be between 1 and 4096 bytes".into(),
            ));
        }
        request.setup_features.sort();
        request.setup_features.dedup();

        let key = RecordKey::new(tenant_id, bundle_id, target_id);
        let target = self
            .inner
            .targets
            .read()
            .expect("Core SSH target lock poisoned")
            .get(&key)
            .cloned()
            .ok_or(BundleSshError::TargetNotFound)?;
        if target.lifecycle_state != SshTargetLifecycleState::Active {
            return Err(BundleSshError::Invalid(
                "SSH setup can be reapplied only to an active target".into(),
            ));
        }
        if target.target_revision != request.expected_target_revision {
            return Err(BundleSshError::TargetRevisionChanged);
        }
        let target_profile_id = target
            .target_profile_id
            .clone()
            .ok_or_else(|| BundleSshError::Invalid("SSH target has no signed profile".into()))?;

        let target_hop = self.prepare_ssh_hop(&target).await?;
        let route_parent = match target.route_parent_target_id.as_deref() {
            Some(parent_id) => {
                let parent_id = LocalId::new(parent_id.to_string())
                    .map_err(|error| BundleSshError::Invalid(error.to_string()))?;
                let parent = self.active_direct_target(tenant_id, bundle_id, &parent_id)?;
                Some(self.prepare_ssh_hop(&parent).await?)
            }
            None => None,
        };
        let connection = BootstrapSshConnection {
            username: target_hop.username,
            ip: target_hop.ip,
            port: target_hop.port,
            alias: target_hop.alias,
            known_hosts_path: target_hop.known_hosts_path,
            private_key_path: target_hop.key_path,
            route_parent,
        };
        let mut stages = Vec::new();
        let os_probe = self
            .run_key_command(
                &connection,
                os_probe_command(),
                None,
                BOOTSTRAP_CONNECT_TIMEOUT,
            )
            .await?;
        require_marker(&os_probe, "detect-os", "__gadgetron_key_ready__")?;
        let os_family = parse_os_family(&os_probe.stdout).to_string();
        if os_family == "unknown" {
            return Err(bootstrap_error(
                "detect-os",
                "automatic monitoring setup supports Debian- and RHEL-family Linux",
            ));
        }
        stages.push(stage("detect-os", format!("Detected {os_family}")));

        let command = setup_command(&os_family, &target.username, &request.setup_features);
        let setup = self
            .run_key_command(
                &connection,
                &command,
                Some(request.sudo_password.as_bytes()),
                BOOTSTRAP_SETUP_TIMEOUT,
            )
            .await?;
        require_marker(&setup, "install-software", "__gadgetron_setup_ready__")?;
        let (installed_packages, skipped_packages) = parse_package_report(&setup.stdout);
        stages.push(stage(
            "install-software",
            format!(
                "Applied {} signed setup features; {} packages unavailable",
                request.setup_features.len(),
                skipped_packages.len()
            ),
        ));

        let verify = self
            .run_key_command(
                &connection,
                &verify_command(&request.setup_features),
                None,
                BOOTSTRAP_CONNECT_TIMEOUT,
            )
            .await?;
        require_marker(&verify, "verify-setup", "__gadgetron_verify_ready__")?;
        stages.push(stage(
            "verify-setup",
            "Verified the signed setup over key-only SSH",
        ));

        Ok(ReapplyBundleSshTargetSetupResponse {
            target_id: target.target_id,
            target_revision: target.target_revision,
            target_profile_id,
            os_family,
            setup_features: request.setup_features.clone(),
            installed_packages,
            skipped_packages,
            stages,
        })
    }

    async fn remove_remote_bootstrap_key(
        &self,
        connection: &BootstrapSshConnection,
        target_id: &str,
    ) -> Result<(), BundleSshError> {
        let Some(private_key_path) = &connection.private_key_path else {
            return Ok(());
        };
        if !private_key_path.is_file() || !connection.known_hosts_path.is_file() {
            return Ok(());
        }
        let command = remove_public_key_command(target_id);
        let output = self
            .run_key_command(connection, &command, None, BOOTSTRAP_CONNECT_TIMEOUT)
            .await?;
        require_marker(&output, "rollback-key", "__gadgetron_key_removed__")
    }

    async fn run_password_command(
        &self,
        connection: &BootstrapSshConnection,
        password: &str,
        remote_command: &str,
        stdin: Option<&[u8]>,
        budget: Duration,
    ) -> Result<CommandOutput, BundleSshError> {
        let mut command = Command::new(SSH_PASS_PATH);
        command
            .kill_on_drop(true)
            .env_clear()
            .env("LANG", "C")
            .env("LC_ALL", "C")
            .env("SSHPASS", password)
            .arg("-e")
            .arg(&self.inner.ssh_path);
        let route_config = if let Some(parent) = &connection.route_parent {
            let child = bootstrap_hop(connection, false);
            let config = self.write_parent_route_config(parent, &child, false)?;
            command
                .arg("-F")
                .arg(config.path())
                .arg("-T")
                .arg(&connection.alias);
            Some(config)
        } else {
            add_common_ssh_arguments(&mut command, connection, false);
            None
        };
        command.arg(remote_command);
        let result = run_command(command, stdin, budget).await;
        drop(route_config);
        result
    }

    async fn run_key_command(
        &self,
        connection: &BootstrapSshConnection,
        remote_command: &str,
        stdin: Option<&[u8]>,
        budget: Duration,
    ) -> Result<CommandOutput, BundleSshError> {
        let mut command = Command::new(&self.inner.ssh_path);
        command
            .kill_on_drop(true)
            .env_clear()
            .env("LANG", "C")
            .env("LC_ALL", "C");
        let route_config = if let Some(parent) = &connection.route_parent {
            let child = bootstrap_hop(connection, true);
            let config = self.write_parent_route_config(parent, &child, true)?;
            command
                .arg("-F")
                .arg(config.path())
                .arg("-T")
                .arg(&connection.alias);
            Some(config)
        } else {
            add_common_ssh_arguments(&mut command, connection, true);
            None
        };
        command.arg(remote_command);
        let result = run_command(command, stdin, budget).await;
        drop(route_config);
        result
    }

    async fn generate_bootstrap_key(
        &self,
        private_key_path: &Path,
        target_id: &str,
    ) -> Result<(), BundleSshError> {
        let output = Command::new(&self.inner.ssh_keygen_path)
            .env_clear()
            .env("LANG", "C")
            .env("LC_ALL", "C")
            .args(["-q", "-t", "ed25519", "-N", "", "-C"])
            .arg(format!("gadgetron-monitor:{target_id}"))
            .arg("-f")
            .arg(private_key_path)
            .stdin(Stdio::null())
            .output()
            .await
            .map_err(|_| BundleSshError::DependencyUnavailable)?;
        if !output.status.success() {
            return Err(bootstrap_error("generate-key", "ssh-keygen failed"));
        }
        Ok(())
    }
}

fn bootstrap_hop(connection: &BootstrapSshConnection, key_only: bool) -> SshHopConfig {
    SshHopConfig {
        alias: connection.alias.clone(),
        ip: connection.ip,
        port: connection.port,
        username: connection.username.clone(),
        key_path: key_only
            .then(|| connection.private_key_path.clone())
            .flatten(),
        known_hosts_path: connection.known_hosts_path.clone(),
    }
}

fn default_bootstrap_address_policy() -> SshAddressPolicy {
    SshAddressPolicy {
        allow_private: true,
        allow_loopback: false,
        allow_link_local: false,
    }
}

fn add_common_ssh_arguments(
    command: &mut Command,
    connection: &BootstrapSshConnection,
    key_only: bool,
) {
    command
        .arg("-F")
        .arg("/dev/null")
        .arg("-T")
        .arg("-p")
        .arg(connection.port.to_string());
    let strict = if key_only { "yes" } else { "accept-new" };
    for option in [
        format!("StrictHostKeyChecking={strict}"),
        format!(
            "UserKnownHostsFile={}",
            connection.known_hosts_path.display()
        ),
        "GlobalKnownHostsFile=/dev/null".to_string(),
        format!("HostKeyAlias={}", connection.alias),
        "HashKnownHosts=no".to_string(),
        "CheckHostIP=no".to_string(),
        "IdentitiesOnly=yes".to_string(),
        "IdentityAgent=none".to_string(),
        "AddKeysToAgent=no".to_string(),
        "ConnectionAttempts=1".to_string(),
        "ConnectTimeout=8".to_string(),
        "ServerAliveInterval=5".to_string(),
        "ServerAliveCountMax=1".to_string(),
        "CanonicalizeHostname=no".to_string(),
        "ProxyCommand=none".to_string(),
        "ProxyJump=none".to_string(),
        "PermitLocalCommand=no".to_string(),
        "LocalCommand=none".to_string(),
        "ClearAllForwardings=yes".to_string(),
        "ForwardAgent=no".to_string(),
        "ForwardX11=no".to_string(),
        "Tunnel=no".to_string(),
        "RequestTTY=no".to_string(),
        "ControlMaster=no".to_string(),
        "Compression=no".to_string(),
        "EscapeChar=none".to_string(),
        "LogLevel=ERROR".to_string(),
    ] {
        command.arg("-o").arg(option);
    }
    if key_only {
        command
            .arg("-o")
            .arg("BatchMode=yes")
            .arg("-o")
            .arg("PasswordAuthentication=no")
            .arg("-o")
            .arg("KbdInteractiveAuthentication=no")
            .arg("-o")
            .arg("PubkeyAuthentication=yes")
            .arg("-o")
            .arg("PreferredAuthentications=publickey")
            .arg("-o")
            .arg("NumberOfPasswordPrompts=0");
        if let Some(path) = &connection.private_key_path {
            command
                .arg("-o")
                .arg(format!("IdentityFile={}", path.display()));
        }
    } else {
        command
            .arg("-o")
            .arg("PubkeyAuthentication=no")
            .arg("-o")
            .arg("PreferredAuthentications=password,keyboard-interactive")
            .arg("-o")
            .arg("NumberOfPasswordPrompts=1");
    }
    command.arg(format!("{}@{}", connection.username, connection.ip));
}

async fn run_command(
    mut command: Command,
    stdin: Option<&[u8]>,
    budget: Duration,
) -> Result<CommandOutput, BundleSshError> {
    command
        .stdin(if stdin.is_some() {
            Stdio::piped()
        } else {
            Stdio::null()
        })
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());
    let mut child = command
        .spawn()
        .map_err(|_| BundleSshError::DependencyUnavailable)?;
    if let Some(bytes) = stdin {
        let mut input = child
            .stdin
            .take()
            .ok_or(BundleSshError::DependencyUnavailable)?;
        input
            .write_all(bytes)
            .await
            .map_err(|_| bootstrap_error("install-software", "cannot send sudo credential"))?;
        input
            .write_all(b"\n")
            .await
            .map_err(|_| bootstrap_error("install-software", "cannot finish sudo credential"))?;
    }
    let stdout = child
        .stdout
        .take()
        .ok_or(BundleSshError::DependencyUnavailable)?;
    let stderr = child
        .stderr
        .take()
        .ok_or(BundleSshError::DependencyUnavailable)?;
    let stdout_task = tokio::spawn(read_bounded(stdout));
    let stderr_task = tokio::spawn(read_bounded(stderr));
    let status = match timeout(budget, child.wait()).await {
        Ok(Ok(status)) => status,
        Ok(Err(_)) => return Err(BundleSshError::DependencyUnavailable),
        Err(_) => {
            let _ = child.kill().await;
            return Err(BundleSshError::Timeout);
        }
    };
    let (stdout, stdout_exceeded) = stdout_task
        .await
        .map_err(|_| BundleSshError::DependencyUnavailable)?
        .map_err(|_| BundleSshError::DependencyUnavailable)?;
    let (stderr, stderr_exceeded) = stderr_task
        .await
        .map_err(|_| BundleSshError::DependencyUnavailable)?
        .map_err(|_| BundleSshError::DependencyUnavailable)?;
    if stdout_exceeded || stderr_exceeded {
        return Err(BundleSshError::OutputLimit);
    }
    Ok(CommandOutput {
        stdout: bounded_text(&stdout),
        stderr: bounded_text(&stderr),
        success: status.success(),
    })
}

async fn read_bounded<R>(mut reader: R) -> std::io::Result<(Vec<u8>, bool)>
where
    R: AsyncRead + Unpin,
{
    let mut captured = Vec::with_capacity(BOOTSTRAP_OUTPUT_LIMIT.min(8 * 1024));
    let mut exceeded = false;
    let mut buffer = [0_u8; 8 * 1024];
    loop {
        let count = reader.read(&mut buffer).await?;
        if count == 0 {
            return Ok((captured, exceeded));
        }
        let remaining = BOOTSTRAP_OUTPUT_LIMIT.saturating_sub(captured.len());
        captured.extend_from_slice(&buffer[..count.min(remaining)]);
        exceeded |= count > remaining;
    }
}

fn bounded_text(bytes: &[u8]) -> String {
    let bytes = &bytes[..bytes.len().min(BOOTSTRAP_OUTPUT_LIMIT)];
    String::from_utf8_lossy(bytes).into_owned()
}

fn require_marker(
    output: &CommandOutput,
    stage: &'static str,
    marker: &str,
) -> Result<(), BundleSshError> {
    if output.success && output.stdout.contains(marker) {
        return Ok(());
    }
    let detail = output
        .stderr
        .lines()
        .last()
        .or_else(|| output.stdout.lines().last())
        .unwrap_or("remote command failed");
    Err(bootstrap_error(stage, detail))
}

fn bootstrap_error(stage: &'static str, detail: impl AsRef<str>) -> BundleSshError {
    BundleSshError::Bootstrap {
        stage,
        detail: detail
            .as_ref()
            .chars()
            .filter(|character| !character.is_control())
            .take(512)
            .collect(),
    }
}

fn attach_rollback_result(
    error: BundleSshError,
    rollback: Result<(), BundleSshError>,
) -> BundleSshError {
    let Err(rollback_error) = rollback else {
        return error;
    };
    match error {
        BundleSshError::Bootstrap { stage, detail } => BundleSshError::Bootstrap {
            stage,
            detail: format!(
                "{}; generated remote key rollback also failed: {}",
                detail,
                bounded_text(rollback_error.to_string().as_bytes())
            ),
        },
        other => BundleSshError::Bootstrap {
            stage: "rollback-key",
            detail: format!("{other}; generated remote key rollback also failed: {rollback_error}"),
        },
    }
}

fn stage(id: &'static str, detail: impl Into<String>) -> BootstrapStage {
    BootstrapStage {
        id,
        status: "succeeded",
        detail: detail.into(),
    }
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

fn install_public_key_command(public_key: &str, target_id: &str) -> String {
    let key = shell_quote(public_key);
    let marker = shell_quote(&format!("gadgetron-monitor:{target_id}"));
    format!(
        "set -eu; umask 077; mkdir -p ~/.ssh; chmod 700 ~/.ssh; touch ~/.ssh/authorized_keys; chmod 600 ~/.ssh/authorized_keys; tmp=$(mktemp ~/.ssh/authorized_keys.XXXXXX); awk -v marker={marker} 'index($0, marker) == 0 {{ print }}' ~/.ssh/authorized_keys > \"$tmp\"; printf '%s\\n' {key} >> \"$tmp\"; chmod 600 \"$tmp\"; mv \"$tmp\" ~/.ssh/authorized_keys; printf '__gadgetron_key_installed__\\n'"
    )
}

fn remove_public_key_command(target_id: &str) -> String {
    let marker = shell_quote(&format!("gadgetron-monitor:{target_id}"));
    format!(
        "set -eu; if [ -f ~/.ssh/authorized_keys ]; then tmp=$(mktemp ~/.ssh/authorized_keys.XXXXXX); awk -v marker={marker} 'index($0, marker) == 0 {{ print }}' ~/.ssh/authorized_keys > \"$tmp\"; chmod 600 \"$tmp\"; mv \"$tmp\" ~/.ssh/authorized_keys; fi; printf '__gadgetron_key_removed__\\n'"
    )
}

fn os_probe_command() -> &'static str {
    "set -eu; family=unknown; if [ -r /etc/os-release ]; then . /etc/os-release; case \"${ID:-} ${ID_LIKE:-}\" in *debian*|*ubuntu*) family=debian;; *rhel*|*fedora*|*centos*|*rocky*|*almalinux*) family=rhel;; esac; fi; printf 'os_family=%s\\n__gadgetron_key_ready__\\n' \"$family\""
}

fn parse_os_family(stdout: &str) -> &str {
    stdout
        .lines()
        .find_map(|line| line.strip_prefix("os_family="))
        .filter(|family| matches!(*family, "debian" | "rhel"))
        .unwrap_or("unknown")
}

fn setup_command(os_family: &str, username: &str, features: &[TargetSetupFeature]) -> String {
    let mut packages = BTreeSet::new();
    if features.contains(&TargetSetupFeature::SystemObservation) {
        for package in match os_family {
            "debian" => [
                "ca-certificates",
                "curl",
                "ethtool",
                "ipmitool",
                "iproute2",
                "jq",
                "lldpd",
                "lm-sensors",
                "pciutils",
                "procps",
                "smartmontools",
            ]
            .as_slice(),
            "rhel" => [
                "ca-certificates",
                "curl",
                "ethtool",
                "ipmitool",
                "iproute",
                "jq",
                "lldpd",
                "lm_sensors",
                "pciutils",
                "procps-ng",
                "smartmontools",
            ]
            .as_slice(),
            _ => &[],
        } {
            packages.insert(*package);
        }
    }
    if features.contains(&TargetSetupFeature::RedisClient) {
        packages.insert(match os_family {
            "debian" => "redis-tools",
            "rhel" => "redis",
            _ => "unsupported-redis-client",
        });
    }
    if features.contains(&TargetSetupFeature::NvidiaDcgm) {
        for package in match os_family {
            "debian" => ["ca-certificates", "curl"].as_slice(),
            "rhel" => ["ca-certificates", "curl", "dnf-plugins-core"].as_slice(),
            _ => &[],
        } {
            packages.insert(*package);
        }
    }
    let package_list = packages.into_iter().collect::<Vec<_>>().join(" ");
    let install = if package_list.is_empty() {
        "true".into()
    } else {
        match os_family {
            "debian" => format!(
                "export DEBIAN_FRONTEND=noninteractive; apt-get update -qq; for pkg in {package_list}; do if apt-get install -y -qq --no-install-recommends \"$pkg\" >/dev/null 2>&1; then echo installed_package=$pkg; else echo skipped_package=$pkg; fi; done"
            ),
            "rhel" => format!(
                "dnf -y -q makecache; for pkg in {package_list}; do if dnf -y -q install \"$pkg\" >/dev/null 2>&1; then echo installed_package=$pkg; else echo skipped_package=$pkg; fi; done"
            ),
            _ => "echo skipped_package=unsupported-os".into(),
        }
    };
    let mut sudo_commands = Vec::new();
    if features.contains(&TargetSetupFeature::SystemObservation) {
        sudo_commands.extend([
            "/usr/sbin/smartctl",
            "/usr/bin/ipmitool",
            "/usr/bin/nvidia-smi",
            "/usr/bin/journalctl",
            "/bin/journalctl",
            "/usr/bin/dmesg",
            "/bin/dmesg",
        ]);
    }
    if features.contains(&TargetSetupFeature::NvidiaDcgm) {
        sudo_commands.push("/usr/bin/dcgmi");
    }
    let sudoers = (!sudo_commands.is_empty()).then(|| {
        format!(
            "{username} ALL=(root) NOPASSWD: {}",
            sudo_commands.join(", ")
        )
    });
    let sudoers_install = sudoers.map_or_else(
        || "true".into(),
        |value| {
            format!(
                "tmp=$(mktemp); printf '%s\\n' {} > \"$tmp\"; chmod 0440 \"$tmp\"; visudo -cf \"$tmp\" >/dev/null; install -m 0440 -o root -g root \"$tmp\" /etc/sudoers.d/gadgetron-monitor; rm -f \"$tmp\"",
                shell_quote(&value)
            )
        },
    );
    let dcgm_install = if features.contains(&TargetSetupFeature::NvidiaDcgm) {
        dcgm_setup_command(os_family)
    } else {
        "true".into()
    };
    let root_script = shell_quote(&format!(
        "set -eu; {install}; {dcgm_install}; {sudoers_install}; printf '__gadgetron_setup_ready__\\n'"
    ));
    let enrollment = if features.contains(&TargetSetupFeature::SystemObservation)
        || features.contains(&TargetSetupFeature::NvidiaDcgm)
    {
        "umask 077; mkdir -p \"$HOME/.local/state/gadgetron-monitor\"; tmp=$(mktemp \"$HOME/.local/state/gadgetron-monitor/enabled.XXXXXX\"); printf 'enabled\\n' > \"$tmp\"; chmod 0600 \"$tmp\"; mv \"$tmp\" \"$HOME/.local/state/gadgetron-monitor/enabled\""
    } else {
        "true"
    };
    format!("sudo -S -p '' /bin/sh -c {root_script} && {enrollment}")
}

fn dcgm_setup_command(os_family: &str) -> String {
    let install = match os_family {
        "debian" => {
            r#"
if ! apt-cache show "$dcgm_package" >/dev/null 2>&1; then
  . /etc/os-release
  case "${ID:-}:${VERSION_ID:-}" in
    ubuntu:22.04) cuda_repo=ubuntu2204;;
    ubuntu:24.04) cuda_repo=ubuntu2404;;
    ubuntu:26.04) cuda_repo=ubuntu2604;;
    debian:12) cuda_repo=debian12;;
    debian:13) cuda_repo=debian13;;
    *) cuda_repo=;;
  esac
  case "$(uname -m)" in x86_64) cuda_arch=x86_64;; aarch64) cuda_arch=sbsa;; *) cuda_arch=;; esac
  if [ -n "$cuda_repo" ] && [ -n "$cuda_arch" ]; then
    keyring=$(mktemp)
    if curl -fsSL "https://developer.download.nvidia.com/compute/cuda/repos/$cuda_repo/$cuda_arch/cuda-keyring_1.1-1_all.deb" -o "$keyring" && dpkg -i "$keyring" >/dev/null 2>&1; then
      echo installed_package=nvidia-cuda-repository
      apt-get update -qq
    fi
    rm -f "$keyring"
  fi
fi
if apt-cache show "$dcgm_package" >/dev/null 2>&1 && apt-get install -y -qq --install-recommends "$dcgm_package" >/dev/null 2>&1; then
  dcgm_installed=1
else
  dcgm_installed=0
fi
"#
        }
        "rhel" => {
            r#"
if ! dnf -q list --available "$dcgm_package" >/dev/null 2>&1; then
  . /etc/os-release
  rhel_major=$(printf '%s' "${VERSION_ID:-}" | cut -d. -f1)
  case "$rhel_major" in 8|9|10) cuda_repo=rhel$rhel_major;; *) cuda_repo=;; esac
  case "$(uname -m)" in x86_64) cuda_arch=x86_64;; aarch64) cuda_arch=sbsa;; *) cuda_arch=;; esac
  if [ -n "$cuda_repo" ] && [ -n "$cuda_arch" ] && dnf config-manager --add-repo "https://developer.download.nvidia.com/compute/cuda/repos/$cuda_repo/$cuda_arch/cuda-$cuda_repo.repo" >/dev/null 2>&1; then
    echo installed_package=nvidia-cuda-repository
    dnf -q clean expire-cache >/dev/null 2>&1 || true
  fi
fi
if dnf -y -q --setopt=install_weak_deps=True install "$dcgm_package" >/dev/null 2>&1; then
  dcgm_installed=1
else
  dcgm_installed=0
fi
"#
        }
        _ => "dcgm_installed=0",
    };
    format!(
        r#"
nvidia_smi=$(command -v nvidia-smi 2>/dev/null || true)
if [ -z "$nvidia_smi" ] && [ -x /usr/lib/wsl/lib/nvidia-smi ]; then nvidia_smi=/usr/lib/wsl/lib/nvidia-smi; fi
if [ -z "$nvidia_smi" ] || ! "$nvidia_smi" -L >/dev/null 2>&1; then
  echo skipped_package=nvidia-dcgm:no-supported-gpu
elif command -v dcgmi >/dev/null 2>&1 && dcgmi discovery -l >/dev/null 2>&1; then
  echo installed_package=nvidia-dcgm:existing
else
  cuda_major=$("$nvidia_smi" -q 2>/dev/null | sed -E -n 's/CUDA Version[ :]+([0-9]+)[.].*/\1/p' | head -n 1)
  if [ -z "$cuda_major" ]; then
    echo skipped_package=nvidia-dcgm:cuda-version-unknown
  else
    if [ "$cuda_major" -ge 13 ] 2>/dev/null; then
      compute_cap=$("$nvidia_smi" --query-gpu=compute_cap --format=csv,noheader,nounits 2>/dev/null | head -n 1)
      case "$compute_cap" in 5.*|6.*|7.0) cuda_major=12;; esac
    fi
    dcgm_package=datacenter-gpu-manager-4-cuda$cuda_major
    dcgm_installed=0
    {install}
    if [ "$dcgm_installed" = 1 ]; then
      if command -v systemctl >/dev/null 2>&1; then systemctl enable --now nvidia-dcgm >/dev/null 2>&1 || true; fi
      if command -v dcgmi >/dev/null 2>&1 && dcgmi discovery -l >/dev/null 2>&1; then
        echo installed_package=$dcgm_package
      else
        echo skipped_package=$dcgm_package:verification-failed
      fi
    else
      echo skipped_package=$dcgm_package:repository-or-install-unavailable
    fi
  fi
fi
"#
    )
    .trim()
    .to_owned()
}

fn verify_command(features: &[TargetSetupFeature]) -> String {
    let mut commands = vec!["command -v sh >/dev/null"];
    if features.contains(&TargetSetupFeature::SystemObservation) {
        commands.extend(["command -v awk >/dev/null", "command -v df >/dev/null"]);
    }
    if features.contains(&TargetSetupFeature::RedisClient) {
        commands.push("command -v redis-cli >/dev/null");
    }
    if features.contains(&TargetSetupFeature::NvidiaDcgm) {
        commands.push(
            "if [ -x /usr/bin/dcgmi ]; then sudo -n /usr/bin/dcgmi discovery -l >/dev/null; fi",
        );
    }
    if features.contains(&TargetSetupFeature::SystemObservation)
        || features.contains(&TargetSetupFeature::NvidiaDcgm)
    {
        commands.push(
            "test \"$(cat \"$HOME/.local/state/gadgetron-monitor/enabled\" 2>/dev/null)\" = enabled",
        );
    }
    format!(
        "set -eu; {}; printf '__gadgetron_verify_ready__\\n'",
        commands.join("; ")
    )
}

fn parse_package_report(stdout: &str) -> (Vec<String>, Vec<String>) {
    let mut installed = Vec::new();
    let mut skipped = Vec::new();
    for line in stdout.lines() {
        if let Some(package) = line.strip_prefix("installed_package=") {
            installed.push(package.to_string());
        } else if let Some(package) = line.strip_prefix("skipped_package=") {
            skipped.push(package.to_string());
        }
    }
    (installed, skipped)
}

fn read_captured_host_key(
    known_hosts_path: &Path,
    alias: &str,
) -> Result<(String, String), BundleSshError> {
    let source = fs::read_to_string(known_hosts_path)
        .map_err(|_| bootstrap_error("capture-host-key", "known_hosts was not created"))?;
    for line in source.lines() {
        let mut fields = line.split_ascii_whitespace();
        let Some(host) = fields.next() else { continue };
        let Some(algorithm) = fields.next() else {
            continue;
        };
        let Some(encoded) = fields.next() else {
            continue;
        };
        if host == alias {
            validate_host_key(algorithm, encoded)?;
            return Ok((algorithm.to_string(), encoded.to_string()));
        }
    }
    Err(bootstrap_error(
        "capture-host-key",
        "the authenticated SSH connection did not yield a host key",
    ))
}

struct StagingDirectory(std::path::PathBuf);

impl Drop for StagingDirectory {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bootstrap_defaults_to_private_network_but_not_loopback_or_link_local() {
        let policy = default_bootstrap_address_policy();
        assert!(policy.allow_private);
        assert!(!policy.allow_loopback);
        assert!(!policy.allow_link_local);
    }

    #[test]
    fn bootstrap_scripts_are_bounded_idempotent_and_do_not_embed_passwords() {
        let key = "ssh-ed25519 AAAAC3Nza test gadgetron-monitor:old";
        let install = install_public_key_command(key, "edge-one");
        assert!(install.contains("authorized_keys"));
        assert!(install.contains("gadgetron-monitor:edge-one"));
        assert!(remove_public_key_command("edge-one").contains("gadgetron-monitor:edge-one"));
        let setup = setup_command(
            "debian",
            "operator",
            &[TargetSetupFeature::SystemObservation],
        );
        assert!(setup.contains("lm-sensors"));
        assert!(setup.contains("smartmontools"));
        assert!(setup.contains("/etc/sudoers.d/gadgetron-monitor"));
        assert!(setup.contains(".local/state/gadgetron-monitor/enabled"));
        assert!(setup.contains("sudo -S"));
        assert!(!setup.contains("PASSWORD"));
        assert!(verify_command(&[TargetSetupFeature::SystemObservation])
            .contains(".local/state/gadgetron-monitor/enabled"));

        let cooling_setup = setup_command("debian", "operator", &[TargetSetupFeature::RedisClient]);
        assert!(cooling_setup.contains("redis-tools"));
        assert!(!cooling_setup.contains("/etc/sudoers.d/gadgetron-monitor"));
        assert!(verify_command(&[TargetSetupFeature::RedisClient]).contains("redis-cli"));

        let dcgm_setup = setup_command(
            "debian",
            "operator",
            &[
                TargetSetupFeature::SystemObservation,
                TargetSetupFeature::NvidiaDcgm,
            ],
        );
        assert!(dcgm_setup.contains("datacenter-gpu-manager-4-cuda"));
        assert!(dcgm_setup.contains("developer.download.nvidia.com/compute/cuda/repos"));
        assert!(dcgm_setup.contains("dcgmi discovery -l"));
        assert!(dcgm_setup.contains("--query-gpu=compute_cap"));
        assert!(dcgm_setup.contains("/usr/bin/dcgmi"));
    }

    #[test]
    fn generated_setup_scripts_have_valid_posix_shell_syntax() {
        for os_family in ["debian", "rhel"] {
            let setup = setup_command(
                os_family,
                "operator",
                &[
                    TargetSetupFeature::SystemObservation,
                    TargetSetupFeature::NvidiaDcgm,
                ],
            );
            let output = std::process::Command::new("/bin/sh")
                .args(["-n", "-c", &setup])
                .output()
                .expect("/bin/sh must be available for generated setup validation");
            assert!(
                output.status.success(),
                "generated {os_family} setup is invalid: {}",
                String::from_utf8_lossy(&output.stderr),
            );
        }
    }

    #[test]
    fn package_report_preserves_installed_and_skipped_items() {
        let (installed, skipped) = parse_package_report(
            "installed_package=jq\nskipped_package=lldpd\n__gadgetron_setup_ready__\n",
        );
        assert_eq!(installed, ["jq"]);
        assert_eq!(skipped, ["lldpd"]);
    }

    #[tokio::test]
    async fn command_output_is_captured_within_the_declared_limit() {
        let (mut writer, reader) = tokio::io::duplex(BOOTSTRAP_OUTPUT_LIMIT + 1);
        writer
            .write_all(&vec![b'x'; BOOTSTRAP_OUTPUT_LIMIT + 1])
            .await
            .unwrap();
        drop(writer);

        let (captured, exceeded) = read_bounded(reader).await.unwrap();
        assert_eq!(captured.len(), BOOTSTRAP_OUTPUT_LIMIT);
        assert!(exceeded);
    }
}
