//! HTTP handler implementations for the OpenAI-compatible gateway endpoints.
//!
//! Handlers are wired into `build_router` in `server.rs`.  Each handler
//! receives shared state via `axum::extract::State<AppState>` and per-request
//! context via `axum::Extension<TenantContext>` (injected by the middleware
//! chain: auth → tenant_context).

use axum::{
    extract::State,
    http::HeaderMap,
    response::{IntoResponse, Response},
    Extension, Json,
};
use gadgetron_core::{
    context::TenantContext,
    error::GadgetronError,
    knowledge::AuthenticatedContext,
    message::{Content, Message, Role},
    provider::{ChatRequest, ModelInfo},
};
use gadgetron_xaas::audit::writer::{AuditEntry, AuditStatus};

use crate::error::ApiError;
use crate::penny::shared_context::render_penny_shared_context;
use crate::server::AppState;
use crate::sse::chat_chunk_to_sse;

// ---------------------------------------------------------------------------
// capture_chat_completion — PSL-1d fire-and-forget helper
// ---------------------------------------------------------------------------

/// Capture a successful chat completion into the activity stream for
/// `<gadgetron_shared_context>` projection on the next turn.
/// Fire-and-forget: errors logged but never propagated.
/// Non-PII: only model name + token counts; no message text.
/// Spec: docs/design/core/knowledge-candidate-curation.md §2.1
#[allow(clippy::too_many_arguments)]
async fn capture_chat_completion(
    coordinator: std::sync::Arc<
        dyn gadgetron_core::knowledge::candidate::KnowledgeCandidateCoordinator,
    >,
    tenant_id: uuid::Uuid,
    request_id: uuid::Uuid,
    // Correlation key for the matching `AuditEntry.event_id`. Generated by
    // the caller once per handler invocation and threaded through both
    // `audit_writer.send()` and this capture call so `audit_log.id ↔
    // captured_activity_event.audit_event_id` JOIN is unambiguous.
    // Drift-fix PR 5 (D-20260418-24) replaced the old `Some(request_id)`
    // reuse; `request_id` stays as the HTTP-request correlation only.
    audit_event_id: uuid::Uuid,
    model: String,
    prompt_tokens: u32,
    completion_tokens: u32,
    stream: bool,
) {
    use gadgetron_core::knowledge::candidate::{
        ActivityKind, ActivityOrigin, CapturedActivityEvent,
    };

    let event = CapturedActivityEvent {
        id: uuid::Uuid::new_v4(),
        tenant_id,
        // TODO(doc-10): real user_id after permission-inheritance lands.
        actor_user_id: uuid::Uuid::nil(),
        request_id: Some(request_id),
        origin: ActivityOrigin::Penny,
        kind: ActivityKind::GadgetToolCall,
        title: format!("chat completion: {model}"),
        summary: format!(
            "{prompt_tokens} input / {completion_tokens} output tokens, stream={stream}"
        ),
        source_bundle: None,
        source_capability: Some("chat.completions".into()),
        // Real audit correlation — matches the AuditEntry.event_id emitted
        // in the same handler invocation. Drift-fix PR 5 (D-20260418-24).
        audit_event_id: Some(audit_event_id),
        facts: serde_json::json!({
            "model": model,
            "stream": stream,
            "prompt_tokens": prompt_tokens,
            "completion_tokens": completion_tokens,
        }),
        created_at: chrono::Utc::now(),
    };

    let actor = AuthenticatedContext;
    if let Err(e) = coordinator.capture_action(&actor, event, vec![]).await {
        tracing::warn!(
            request_id = %request_id,
            error = %e,
            "penny_shared_context.capture_chat_failed"
        );
    }
}

// ---------------------------------------------------------------------------
// capture_chat_completion_error — PSL-1d Err-arm helper
// ---------------------------------------------------------------------------

/// Derive a short, non-PII error class string from a `GadgetronError` variant.
/// Uses the enum discriminant name only — never the message or nested fields,
/// which may contain user-facing strings or path fragments.
fn error_class(e: &GadgetronError) -> &'static str {
    match e {
        GadgetronError::Provider(_) => "provider_error",
        GadgetronError::Routing(_) => "routing_error",
        GadgetronError::QuotaExceeded { .. } => "quota_exceeded",
        GadgetronError::TenantNotFound => "tenant_not_found",
        GadgetronError::Forbidden => "forbidden",
        GadgetronError::Database { .. } => "database_error",
        GadgetronError::StreamInterrupted { .. } => "stream_interrupted",
        GadgetronError::Knowledge { .. } => "knowledge_error",
        GadgetronError::Wiki { .. } => "wiki_error",
        GadgetronError::Penny { .. } => "penny_error",
        _ => "internal_error",
    }
}

/// Capture a failed non-streaming chat completion into the activity stream.
/// Fire-and-forget: errors logged but never propagated.
/// Non-PII: only model name + error class + latency; no message text.
/// Spec: docs/design/core/knowledge-candidate-curation.md §2.1, W3-KC-1c
#[allow(clippy::too_many_arguments)]
async fn capture_chat_completion_error(
    coordinator: std::sync::Arc<
        dyn gadgetron_core::knowledge::candidate::KnowledgeCandidateCoordinator,
    >,
    tenant_id: uuid::Uuid,
    request_id: uuid::Uuid,
    // Correlation key for the matching error `AuditEntry.event_id`.
    // Drift-fix PR 5 (D-20260418-24) — see `capture_chat_completion` for
    // rationale.
    audit_event_id: uuid::Uuid,
    model: String,
    error_class_str: &'static str,
    latency_ms: i32,
) {
    use gadgetron_core::knowledge::candidate::{
        ActivityKind, ActivityOrigin, CapturedActivityEvent,
    };

    let event = CapturedActivityEvent {
        id: uuid::Uuid::new_v4(),
        tenant_id,
        // TODO(doc-10): real user_id after permission-inheritance lands.
        actor_user_id: uuid::Uuid::nil(),
        request_id: Some(request_id),
        origin: ActivityOrigin::Penny,
        kind: ActivityKind::RuntimeObservation,
        title: format!("chat completion failed: {model}"),
        summary: format!("error_class={error_class_str}, latency_ms={latency_ms}"),
        source_bundle: None,
        source_capability: Some("chat.completions".into()),
        audit_event_id: Some(audit_event_id),
        facts: serde_json::json!({
            "model": model,
            "error_class": error_class_str,
            "latency_ms": latency_ms,
        }),
        created_at: chrono::Utc::now(),
    };

    let actor = gadgetron_core::knowledge::AuthenticatedContext;
    if let Err(e) = coordinator.capture_action(&actor, event, vec![]).await {
        tracing::warn!(
            request_id = %request_id,
            error = %e,
            "penny_shared_context.capture_chat_error_failed"
        );
    }
}

// ---------------------------------------------------------------------------
// POST /v1/chat/completions
// ---------------------------------------------------------------------------

/// `POST /v1/chat/completions` — OpenAI-compatible chat handler.
///
/// Routing logic:
/// - `req.stream == false` → calls `router.chat()` → returns `Json<ChatResponse>` (200).
/// - `req.stream == true`  → calls `router.chat_stream()` → pipes through
///   `chat_chunk_to_sse` → returns `Sse<...>` with `Content-Type: text/event-stream`.
///
/// Error paths (all use `ApiError(GadgetronError)` → `IntoResponse`):
/// - `AppState.router` is `None`  → `GadgetronError::Routing` → 503.
/// - `quota_enforcer.check_pre` fails → `GadgetronError::QuotaExceeded` → 429.
/// - `router.chat()` fails → appropriate `GadgetronError` → matching HTTP status.
///
/// Quota and audit are recorded fire-and-forget after dispatch.
pub async fn chat_completions_handler(
    State(state): State<AppState>,
    Extension(ctx): Extension<TenantContext>,
    headers: HeaderMap,
    Json(mut req): Json<ChatRequest>,
) -> Response {
    // Inject conversation_id from header if not set in body.
    // Frontend sends X-Gadgetron-Conversation-Id for session continuity.
    if req.conversation_id.is_none() {
        if let Some(val) = headers.get("x-gadgetron-conversation-id") {
            if let Ok(s) = val.to_str() {
                let s = s.trim();
                if !s.is_empty() && s.len() <= 256 {
                    req.conversation_id = Some(s.to_string());
                }
            }
        }
    }

    // W3-PSL-1b: inject shared-context bootstrap before dispatch.
    // Graceful degrade: never 5xx the chat endpoint on bootstrap failure.
    // Authority: docs/design/phase2/13-penny-shared-surface-loop.md §2.2.2,
    // §2.2.4, §2.2.5.
    let shared_cfg = &state.agent_config.shared_context;
    if shared_cfg.enabled {
        if let Some(assembler) = state.penny_assembler.as_ref() {
            let actor = AuthenticatedContext;
            match assembler
                .build(&actor, req.conversation_id.as_deref(), ctx.request_id)
                .await
            {
                Ok(bootstrap) => {
                    let block = render_penny_shared_context(
                        &bootstrap,
                        shared_cfg.digest_summary_chars as usize,
                    );
                    let injection_mode = inject_shared_context_block(&mut req.messages, &block);
                    // Record a tracing event for observability. Using
                    // `tracing::info!` (not info_span!) because we want an
                    // event; the handler already runs inside the TraceLayer span.
                    tracing::info!(
                        target: "penny_shared_context.inject",
                        request_id = %ctx.request_id,
                        health = ?bootstrap.health,
                        degraded_reasons = bootstrap.degraded_reasons.len(),
                        rendered_bytes = block.len(),
                        injection_mode = %injection_mode,
                        "shared context block injected"
                    );
                }
                Err(e) => {
                    tracing::warn!(
                        target: "penny_shared_context",
                        request_id = %ctx.request_id,
                        error = %e,
                        "penny_shared_context.build_failed — degrading gracefully"
                    );
                    // Continue with original req; do NOT fail the chat request.
                }
            }
        }
    }

    // 1. Resolve the LLM router — return 503 if not configured.
    let router = match &state.router {
        Some(r) => r.clone(),
        None => {
            return ApiError(GadgetronError::Routing(
                "no LLM router configured".to_string(),
            ))
            .into_response();
        }
    };

    // 2. Pre-flight quota check.
    let quota_token = match state
        .quota_enforcer
        .check_pre(ctx.tenant_id, &ctx.quota_snapshot)
        .await
    {
        Ok(t) => t,
        Err(e) => return ApiError(e).into_response(),
    };

    if req.stream {
        handle_streaming(state, ctx, req, router, quota_token).await
    } else {
        handle_non_streaming(state, ctx, req, router, quota_token).await
    }
}

/// Non-streaming path: `router.chat()` → `Json<ChatResponse>`.
async fn handle_non_streaming(
    state: AppState,
    ctx: TenantContext,
    req: ChatRequest,
    router: std::sync::Arc<gadgetron_router::Router>,
    quota_token: gadgetron_xaas::quota::enforcer::QuotaToken,
) -> Response {
    match router.chat(req.clone()).await {
        Ok(response) => {
            let latency_ms = ctx.started_at.elapsed().as_millis() as i32;
            let cost_cents = 0i64;
            // Drift-fix PR 5 (D-20260418-24): generate the audit correlation
            // key ONCE per outcome so both the audit row and the capture
            // event share an unambiguous identity.
            let audit_event_id = uuid::Uuid::new_v4();

            // Fire-and-forget: quota post-record and audit log.
            state
                .quota_enforcer
                .record_post(&quota_token, cost_cents)
                .await;
            state.audit_writer.send(AuditEntry {
                event_id: audit_event_id,
                tenant_id: ctx.tenant_id,
                api_key_id: ctx.api_key_id,
                request_id: ctx.request_id,
                model: Some(req.model.clone()),
                provider: None,
                status: AuditStatus::Ok,
                input_tokens: response.usage.prompt_tokens as i32,
                output_tokens: response.usage.completion_tokens as i32,
                cost_cents,
                latency_ms,
            });

            // PSL-1d: fire-and-forget capture on successful non-streaming chat.
            // Authority: docs/design/core/knowledge-candidate-curation.md §2.1,
            // D-20260418-20. No capture on Err arm (success-only, this PR).
            if let Some(coord) = state.candidate_coordinator.clone() {
                let tenant_id = ctx.tenant_id;
                let request_id = ctx.request_id;
                let model = req.model.clone();
                let prompt_tokens = response.usage.prompt_tokens;
                let completion_tokens = response.usage.completion_tokens;
                tokio::spawn(async move {
                    capture_chat_completion(
                        coord,
                        tenant_id,
                        request_id,
                        audit_event_id,
                        model,
                        prompt_tokens,
                        completion_tokens,
                        false,
                    )
                    .await;
                });
            }

            Json(response).into_response()
        }
        Err(e) => {
            let latency_ms = ctx.started_at.elapsed().as_millis() as i32;
            let audit_event_id = uuid::Uuid::new_v4();

            state.audit_writer.send(AuditEntry {
                event_id: audit_event_id,
                tenant_id: ctx.tenant_id,
                api_key_id: ctx.api_key_id,
                request_id: ctx.request_id,
                model: Some(req.model.clone()),
                provider: None,
                status: AuditStatus::Error,
                input_tokens: 0,
                output_tokens: 0,
                cost_cents: 0,
                latency_ms,
            });

            // PSL-1d / KC-1c: fire-and-forget error capture for non-streaming.
            // Streaming error capture requires a Drop-guard (out of scope, W3-KC-1d).
            if let Some(coord) = state.candidate_coordinator.clone() {
                let tenant_id = ctx.tenant_id;
                let request_id = ctx.request_id;
                let model = req.model.clone();
                let ec = error_class(&e);
                tokio::spawn(async move {
                    capture_chat_completion_error(
                        coord,
                        tenant_id,
                        request_id,
                        audit_event_id,
                        model,
                        ec,
                        latency_ms,
                    )
                    .await;
                });
            }

            ApiError(e).into_response()
        }
    }
}

/// Streaming path: `router.chat_stream()` → SSE pipeline.
///
/// Quota and audit are recorded at dispatch time (A4: time-to-first-byte
/// semantics).  Phase 2 will add a Drop guard on the SSE stream to record
/// total stream duration after the last byte.
async fn handle_streaming(
    state: AppState,
    ctx: TenantContext,
    req: ChatRequest,
    router: std::sync::Arc<gadgetron_router::Router>,
    quota_token: gadgetron_xaas::quota::enforcer::QuotaToken,
) -> Response {
    // Measure dispatch latency BEFORE spawning the audit task (previous bug:
    // the value was captured inside tokio::spawn, always yielding 0ms).
    //
    // KNOWN Phase 1 BEHAVIOR (not a bug — documented for operators):
    //   latency_ms captures ONLY middleware chain + dispatch overhead (sub-millisecond
    //   on current hardware). Streaming total duration is NOT measured because the
    //   audit entry is fired before the first byte leaves the server.
    //
    //   For real end-to-end latency, use:
    //   - `metrics_middleware` → TUI RequestLog broadcast (measures full chain)
    //   - `/metrics` Prometheus histogram (Phase 2)
    //   - Client-side timing (current best option)
    //
    //   Phase 2: wrap the SSE stream in a Drop guard that captures total duration
    //   and accumulates output_tokens from the final stream chunk.
    let latency_ms = ctx.started_at.elapsed().as_millis() as i32;
    let stream = router.chat_stream(req.clone());
    // Drift-fix PR 5 (D-20260418-24): generate the audit correlation key
    // once at dispatch time. When the Phase-2 Drop-guard lands (PR 6) the
    // stream-end amendment will emit a SECOND AuditEntry with a fresh
    // event_id but the same request_id — that's exactly why the two
    // identities have to diverge.
    let audit_event_id = uuid::Uuid::new_v4();

    // Fire-and-forget: quota and audit at dispatch time (A4 semantics).
    let audit_writer = state.audit_writer.clone();
    let quota_enforcer = state.quota_enforcer.clone();
    let tenant_id = ctx.tenant_id;
    let api_key_id = ctx.api_key_id;
    let request_id = ctx.request_id;
    let model = req.model.clone();

    tokio::spawn(async move {
        quota_enforcer.record_post(&quota_token, 0).await;
        audit_writer.send(AuditEntry {
            event_id: audit_event_id,
            tenant_id,
            api_key_id,
            request_id,
            model: Some(model),
            provider: None,
            status: AuditStatus::Ok,
            input_tokens: 0,
            output_tokens: 0,
            cost_cents: 0,
            latency_ms,
        });
    });

    // PSL-1d: fire-and-forget capture at dispatch time for streaming path.
    // Streaming usage counts are 0 here (deferred to Phase-2 Drop-guard).
    // Authority: docs/design/core/knowledge-candidate-curation.md §2.1,
    // D-20260418-20.
    if let Some(coord) = state.candidate_coordinator.clone() {
        let tenant_id_cap = ctx.tenant_id;
        let request_id_cap = ctx.request_id;
        let model_cap = req.model.clone();
        tokio::spawn(async move {
            // Streaming usage counts deferred to Phase-2 Drop-guard.
            capture_chat_completion(
                coord,
                tenant_id_cap,
                request_id_cap,
                audit_event_id,
                model_cap,
                0,
                0,
                true,
            )
            .await;
        });
    }

    chat_chunk_to_sse(stream).into_response()
}

// ---------------------------------------------------------------------------
// GET /v1/models
// ---------------------------------------------------------------------------

/// `GET /v1/models` — OpenAI-compatible model listing.
///
/// Aggregates models from all configured providers via `router.list_models()`.
/// Falls back to direct provider iteration when `router` is `None`.
///
/// Response shape: `{"object": "list", "data": [{...}, ...]}`
pub async fn list_models_handler(State(state): State<AppState>) -> Response {
    let models: Vec<ModelInfo> = if let Some(router) = &state.router {
        match router.list_models().await {
            Ok(m) => m,
            Err(e) => return ApiError(e).into_response(),
        }
    } else {
        // Fallback: iterate providers directly (used in tests with router=None).
        let mut all = Vec::new();
        for provider in state.providers.values() {
            if let Ok(m) = provider.models().await {
                all.extend(m);
            }
        }
        all
    };

    let data: Vec<serde_json::Value> = models
        .iter()
        .map(|m| {
            serde_json::json!({
                "id": m.id,
                "object": m.object,
                "owned_by": m.owned_by,
            })
        })
        .collect();

    Json(serde_json::json!({
        "object": "list",
        "data": data,
    }))
    .into_response()
}

// ---------------------------------------------------------------------------
// inject_shared_context_block — PSL-1b helper
// ---------------------------------------------------------------------------

/// Prepend the shared-context block to a chat message slice.
///
/// Returns a tracing label for the injection mode:
///
/// - `"prepend_to_system"` — the first message was a `System` message with
///   `Content::Text`; the block was prepended to its text.
/// - `"insert_new_system"` — no suitable system message was found at index 0
///   (empty vec, first message is not System, or first message is System with
///   `Content::Parts`); a new `Message::system(block)` was inserted at index 0.
///
/// Rule for `Content::Parts` system messages: inserting a new system message
/// ahead of a Parts system message keeps structured parts intact.
fn inject_shared_context_block(messages: &mut Vec<Message>, block: &str) -> &'static str {
    if let Some(first) = messages.first_mut() {
        if first.role == Role::System {
            if let Content::Text(text) = &mut first.content {
                let mut prefixed = String::with_capacity(block.len() + 2 + text.len());
                prefixed.push_str(block);
                prefixed.push_str("\n\n");
                prefixed.push_str(text);
                *text = prefixed;
                return "prepend_to_system";
            }
            // System message with Parts content — insert a new system msg
            // ahead of it so we don't mangle structured parts.
        }
    }
    messages.insert(0, Message::system(block));
    "insert_new_system"
}

// ---------------------------------------------------------------------------
// Tests — TDD (written before full integration, red → green)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    use async_trait::async_trait;
    use axum::{
        body::Body,
        http::{Request, StatusCode},
        Router,
    };
    use futures::stream;
    use gadgetron_core::{
        agent::config::AgentConfig,
        context::Scope,
        error::GadgetronError,
        message::{Content, ContentPart, Message, Role},
        provider::{
            ChatChunk, ChatRequest, ChatResponse, Choice, ChunkChoice, ChunkDelta, LlmProvider,
            ModelInfo, Usage,
        },
    };
    use gadgetron_router::{router::Router as LlmRouter, MetricsStore};
    use gadgetron_xaas::{
        audit::writer::AuditWriter,
        auth::validator::{KeyValidator, ValidatedKey},
        quota::enforcer::InMemoryQuotaEnforcer,
    };
    use std::{collections::HashMap, sync::Arc};
    use tower::ServiceExt;
    use uuid::Uuid;

    use crate::penny::shared_context::{
        DefaultPennyTurnContextAssembler, PennySharedSurfaceService,
    };
    use crate::test_helpers::{lazy_pool, TEST_AUDIT_CAPACITY, VALID_TOKEN};
    use gadgetron_core::agent::shared_context::PennyTurnContextAssembler;

    // -----------------------------------------------------------------------
    // Constants for FakeLlmProvider fixed responses
    // -----------------------------------------------------------------------

    /// Stable chat-completion ID used across the two fake SSE chunks.
    const FAKE_CHAT_ID: &str = "chatcmpl-test-001";
    /// Unix timestamp embedded in fake responses (2023-11-14 22:13:20 UTC).
    const FAKE_CREATED_TS: u64 = 1_700_000_000;
    /// Model name used by the deterministic `FakeLlmProvider`.
    const FAKE_MODEL_NAME: &str = "fake-model";
    /// `owned_by` field for `ModelInfo` entries returned by `FakeLlmProvider`.
    const FAKE_PROVIDER_ORG: &str = "fake-org";

    // -----------------------------------------------------------------------
    // FakeLlmProvider — deterministic test double for LlmProvider
    // -----------------------------------------------------------------------

    /// Fake provider that returns a fixed `ChatResponse` and a 2-chunk stream.
    ///
    /// Cannot be replaced by `gadgetron_testing::FakeLlmProvider` because
    /// `gadgetron-testing` depends on `gadgetron-gateway` (circular dependency).
    struct FakeLlmProvider {
        model_name: String,
    }

    impl FakeLlmProvider {
        fn new(model_name: impl Into<String>) -> Self {
            Self {
                model_name: model_name.into(),
            }
        }

        fn fixed_response() -> ChatResponse {
            ChatResponse {
                id: FAKE_CHAT_ID.to_string(),
                object: "chat.completion".to_string(),
                created: FAKE_CREATED_TS,
                model: FAKE_MODEL_NAME.to_string(),
                choices: vec![Choice {
                    index: 0,
                    message: Message {
                        role: Role::Assistant,
                        content: Content::Text("Hello from FakeLlmProvider!".to_string()),
                        reasoning_content: None,
                    },
                    finish_reason: Some("stop".to_string()),
                }],
                usage: Usage {
                    prompt_tokens: 10,
                    completion_tokens: 7,
                    total_tokens: 17,
                },
            }
        }

        fn fixed_chunks() -> Vec<ChatChunk> {
            vec![
                ChatChunk {
                    id: FAKE_CHAT_ID.to_string(),
                    object: "chat.completion.chunk".to_string(),
                    created: FAKE_CREATED_TS,
                    model: FAKE_MODEL_NAME.to_string(),
                    choices: vec![ChunkChoice {
                        index: 0,
                        delta: ChunkDelta {
                            role: Some("assistant".to_string()),
                            content: Some("Hello".to_string()),
                            tool_calls: None,
                            reasoning_content: None,
                        },
                        finish_reason: None,
                    }],
                },
                ChatChunk {
                    id: FAKE_CHAT_ID.to_string(),
                    object: "chat.completion.chunk".to_string(),
                    created: FAKE_CREATED_TS,
                    model: FAKE_MODEL_NAME.to_string(),
                    choices: vec![ChunkChoice {
                        index: 0,
                        delta: ChunkDelta {
                            role: None,
                            content: Some(" World!".to_string()),
                            tool_calls: None,
                            reasoning_content: None,
                        },
                        finish_reason: Some("stop".to_string()),
                    }],
                },
            ]
        }
    }

    #[async_trait]
    impl LlmProvider for FakeLlmProvider {
        async fn chat(&self, _req: ChatRequest) -> gadgetron_core::error::Result<ChatResponse> {
            Ok(Self::fixed_response())
        }

        fn chat_stream(
            &self,
            _req: ChatRequest,
        ) -> std::pin::Pin<
            Box<dyn futures::Stream<Item = gadgetron_core::error::Result<ChatChunk>> + Send>,
        > {
            let chunks = Self::fixed_chunks();
            Box::pin(stream::iter(chunks.into_iter().map(Ok)))
        }

        async fn models(&self) -> gadgetron_core::error::Result<Vec<ModelInfo>> {
            Ok(vec![ModelInfo {
                id: self.model_name.clone(),
                object: "model".to_string(),
                owned_by: FAKE_PROVIDER_ORG.to_string(),
            }])
        }

        fn name(&self) -> &str {
            "fake"
        }

        async fn health(&self) -> gadgetron_core::error::Result<()> {
            Ok(())
        }
    }

    // -----------------------------------------------------------------------
    // FakeErrorProvider — returns StreamInterrupted for chat_stream
    // -----------------------------------------------------------------------

    struct FakeErrorProvider;

    #[async_trait]
    impl LlmProvider for FakeErrorProvider {
        async fn chat(&self, _req: ChatRequest) -> gadgetron_core::error::Result<ChatResponse> {
            Err(GadgetronError::Provider("fake error".to_string()))
        }

        fn chat_stream(
            &self,
            _req: ChatRequest,
        ) -> std::pin::Pin<
            Box<dyn futures::Stream<Item = gadgetron_core::error::Result<ChatChunk>> + Send>,
        > {
            Box::pin(stream::iter(vec![Err(GadgetronError::StreamInterrupted {
                reason: "fake stream error".to_string(),
            })]))
        }

        async fn models(&self) -> gadgetron_core::error::Result<Vec<ModelInfo>> {
            Ok(vec![])
        }

        fn name(&self) -> &str {
            "fake-error"
        }

        async fn health(&self) -> gadgetron_core::error::Result<()> {
            Err(GadgetronError::Provider("unhealthy".to_string()))
        }
    }

    // -----------------------------------------------------------------------
    // Auth doubles
    // -----------------------------------------------------------------------

    struct AlwaysAcceptValidator {
        key: Arc<ValidatedKey>,
    }

    impl AlwaysAcceptValidator {
        fn new(scopes: Vec<Scope>) -> Self {
            Self {
                key: Arc::new(ValidatedKey {
                    api_key_id: Uuid::new_v4(),
                    tenant_id: Uuid::new_v4(),
                    scopes,
                }),
            }
        }
    }

    #[async_trait]
    impl KeyValidator for AlwaysAcceptValidator {
        async fn validate(
            &self,
            _key_hash: &str,
        ) -> gadgetron_core::error::Result<Arc<ValidatedKey>> {
            Ok(self.key.clone())
        }
        async fn invalidate(&self, _key_hash: &str) {}
    }

    // -----------------------------------------------------------------------
    // Test helpers
    // -----------------------------------------------------------------------

    /// Build an `AppState` with the given `LlmProvider` wired into a `Router`.
    fn make_state_with_provider(
        provider: impl LlmProvider + 'static,
        provider_name: &str,
    ) -> AppState {
        let (audit_writer, _rx) = AuditWriter::new(TEST_AUDIT_CAPACITY);
        let mut providers: HashMap<String, Arc<dyn LlmProvider>> = HashMap::new();
        providers.insert(provider_name.to_string(), Arc::new(provider));

        let metrics = Arc::new(MetricsStore::new());
        let routing_config = gadgetron_core::routing::RoutingConfig {
            default_strategy: gadgetron_core::routing::RoutingStrategy::RoundRobin,
            fallbacks: HashMap::new(),
            costs: HashMap::new(),
        };
        let lrouter = LlmRouter::new(providers.clone(), routing_config, metrics);

        let providers_for_state: HashMap<String, Arc<dyn LlmProvider + Send + Sync>> = providers
            .into_iter()
            .map(|(k, v)| (k, v as Arc<dyn LlmProvider + Send + Sync>))
            .collect();

        AppState {
            key_validator: Arc::new(AlwaysAcceptValidator::new(vec![Scope::OpenAiCompat])),
            quota_enforcer: Arc::new(InMemoryQuotaEnforcer),
            audit_writer: Arc::new(audit_writer),
            providers: Arc::new(providers_for_state),
            router: Some(Arc::new(lrouter)),
            pg_pool: Some(lazy_pool()),
            no_db: false,
            tui_tx: None,
            workbench: None,
            penny_shared_surface: None,
            agent_config: Arc::new(AgentConfig::default()),
            penny_assembler: None,
            activity_capture_store: None,
            candidate_coordinator: None,
        }
    }

    /// Build the full axum `Router` from an `AppState` that has a real provider.
    fn build_test_app(state: AppState) -> Router {
        crate::server::build_router(state)
    }

    /// Minimal valid `ChatRequest` JSON body.
    fn chat_request_body(stream: bool) -> serde_json::Value {
        serde_json::json!({
            "model": "fake-model",
            "messages": [{"role": "user", "content": "hi"}],
            "stream": stream
        })
    }

    // -----------------------------------------------------------------------
    // S3-4 required TDD tests
    // -----------------------------------------------------------------------

    /// `POST /v1/chat/completions` with `stream: false` returns HTTP 200
    /// and a valid `ChatResponse` JSON body.
    #[tokio::test]
    async fn non_streaming_returns_json_response() {
        let state = make_state_with_provider(FakeLlmProvider::new("fake-model"), "fake");
        let app = build_test_app(state);

        let body_json = serde_json::to_vec(&chat_request_body(false)).unwrap();
        let req = Request::builder()
            .method("POST")
            .uri("/v1/chat/completions")
            .header("content-type", "application/json")
            .header("authorization", format!("Bearer {VALID_TOKEN}"))
            .body(Body::from(body_json))
            .unwrap();

        let resp = app.oneshot(req).await.unwrap();
        assert_eq!(
            resp.status(),
            StatusCode::OK,
            "non-streaming must return 200"
        );

        let body = axum::body::to_bytes(resp.into_body(), usize::MAX)
            .await
            .unwrap();
        let value: serde_json::Value = serde_json::from_slice(&body).unwrap();

        // Verify OpenAI-compatible shape.
        assert_eq!(value["object"], "chat.completion");
        assert!(value["id"].is_string(), "id must be present");
        assert!(value["choices"].is_array(), "choices must be an array");
        assert!(!value["choices"].as_array().unwrap().is_empty());
        assert!(value["usage"]["prompt_tokens"].is_number());
    }

    /// `POST /v1/chat/completions` with `stream: true` returns HTTP 200
    /// and `Content-Type: text/event-stream`.
    #[tokio::test]
    async fn streaming_returns_sse_content_type() {
        let state = make_state_with_provider(FakeLlmProvider::new("fake-model"), "fake");
        let app = build_test_app(state);

        let body_json = serde_json::to_vec(&chat_request_body(true)).unwrap();
        let req = Request::builder()
            .method("POST")
            .uri("/v1/chat/completions")
            .header("content-type", "application/json")
            .header("authorization", format!("Bearer {VALID_TOKEN}"))
            .body(Body::from(body_json))
            .unwrap();

        let resp = app.oneshot(req).await.unwrap();
        assert_eq!(resp.status(), StatusCode::OK, "streaming must return 200");

        let ct = resp
            .headers()
            .get("content-type")
            .expect("content-type header must be present")
            .to_str()
            .unwrap();
        assert!(
            ct.contains("text/event-stream"),
            "content-type must be text/event-stream, got: {ct}"
        );
    }

    /// A normal streaming response ends with `data: [DONE]`.
    ///
    /// We drive the full SSE body and confirm the last non-empty data line
    /// is `data: [DONE]`.
    #[tokio::test]
    async fn sse_stream_ends_with_done() {
        let state = make_state_with_provider(FakeLlmProvider::new("fake-model"), "fake");
        let app = build_test_app(state);

        let body_json = serde_json::to_vec(&chat_request_body(true)).unwrap();
        let req = Request::builder()
            .method("POST")
            .uri("/v1/chat/completions")
            .header("content-type", "application/json")
            .header("authorization", format!("Bearer {VALID_TOKEN}"))
            .body(Body::from(body_json))
            .unwrap();

        let resp = app.oneshot(req).await.unwrap();
        assert_eq!(resp.status(), StatusCode::OK);

        let body_bytes = axum::body::to_bytes(resp.into_body(), usize::MAX)
            .await
            .unwrap();
        let body_str = std::str::from_utf8(&body_bytes).unwrap();

        // SSE frames are separated by "\n\n".  Collect all `data:` lines.
        let data_lines: Vec<&str> = body_str
            .lines()
            .filter(|l| l.starts_with("data:"))
            .collect();

        assert!(
            !data_lines.is_empty(),
            "SSE response must contain at least one data: line"
        );

        let last = *data_lines.last().unwrap();
        assert_eq!(
            last.trim(),
            "data: [DONE]",
            "last SSE frame must be 'data: [DONE]', got: {last:?}"
        );
    }

    /// A stream that errors emits an `event: error` SSE frame and does NOT
    /// emit `data: [DONE]`.
    #[tokio::test]
    async fn sse_error_emits_error_event() {
        let state = make_state_with_provider(FakeErrorProvider, "fake-error");
        let app = build_test_app(state);

        let body_json = serde_json::to_vec(&chat_request_body(true)).unwrap();
        let req = Request::builder()
            .method("POST")
            .uri("/v1/chat/completions")
            .header("content-type", "application/json")
            .header("authorization", format!("Bearer {VALID_TOKEN}"))
            .body(Body::from(body_json))
            .unwrap();

        let resp = app.oneshot(req).await.unwrap();
        // The SSE response itself is HTTP 200 — errors are signalled inside the stream.
        assert_eq!(resp.status(), StatusCode::OK);

        let body_bytes = axum::body::to_bytes(resp.into_body(), usize::MAX)
            .await
            .unwrap();
        let body_str = std::str::from_utf8(&body_bytes).unwrap();

        // There must be an `event: error` frame.
        assert!(
            body_str.contains("event: error"),
            "SSE body must contain 'event: error', got:\n{body_str}"
        );

        // `data: [DONE]` must NOT appear after an error (P3 decision).
        assert!(
            !body_str.contains("[DONE]"),
            "SSE body must NOT contain [DONE] after an error, got:\n{body_str}"
        );
    }

    /// `GET /v1/models` returns HTTP 200 with a non-empty model list that
    /// includes the model registered on `FakeLlmProvider`.
    #[tokio::test]
    async fn list_models_returns_configured_models() {
        let state = make_state_with_provider(FakeLlmProvider::new("fake-gpt-4"), "fake");
        let app = build_test_app(state);

        let req = Request::builder()
            .method("GET")
            .uri("/v1/models")
            .header("authorization", format!("Bearer {VALID_TOKEN}"))
            .body(Body::empty())
            .unwrap();

        let resp = app.oneshot(req).await.unwrap();
        assert_eq!(resp.status(), StatusCode::OK, "list_models must return 200");

        let body = axum::body::to_bytes(resp.into_body(), usize::MAX)
            .await
            .unwrap();
        let value: serde_json::Value = serde_json::from_slice(&body).unwrap();

        assert_eq!(value["object"], "list", "envelope object must be 'list'");
        let data = value["data"].as_array().expect("data must be an array");
        assert!(
            !data.is_empty(),
            "data must contain at least one model entry"
        );

        let ids: Vec<&str> = data.iter().filter_map(|m| m["id"].as_str()).collect();
        assert!(
            ids.contains(&"fake-gpt-4"),
            "model 'fake-gpt-4' must appear in the listing, got: {ids:?}"
        );
    }

    // -----------------------------------------------------------------------
    // PSL-1b: inject_shared_context_block unit tests
    // -----------------------------------------------------------------------

    const TEST_BLOCK: &str =
        "<gadgetron_shared_context>\nhealth: healthy\n</gadgetron_shared_context>";

    /// Prepend to existing system message that has Text content.
    /// After injection, content must start with the block and end with
    /// the original system text.
    #[test]
    fn inject_prepends_to_existing_system_message_with_text_content() {
        let original_text = "you are helpful";
        let mut messages = vec![Message::system(original_text), Message::user("hi")];
        let mode = inject_shared_context_block(&mut messages, TEST_BLOCK);
        assert_eq!(mode, "prepend_to_system");
        assert_eq!(messages.len(), 2, "no new messages should be inserted");
        match &messages[0].content {
            Content::Text(text) => {
                assert!(
                    text.starts_with(TEST_BLOCK),
                    "content must start with block; got: {text:?}"
                );
                assert!(
                    text.ends_with(original_text),
                    "content must end with original text; got: {text:?}"
                );
                assert!(
                    text.contains("\n\n"),
                    "block and original must be separated by \\n\\n"
                );
            }
            other => panic!("expected Content::Text, got {other:?}"),
        }
    }

    /// Insert new system message when messages vec starts with a user message.
    #[test]
    fn inject_inserts_new_system_when_messages_empty_of_system() {
        let mut messages = vec![Message::user("hi")];
        let mode = inject_shared_context_block(&mut messages, TEST_BLOCK);
        assert_eq!(mode, "insert_new_system");
        assert_eq!(messages.len(), 2, "a new system message must be prepended");
        assert_eq!(
            messages[0].role,
            Role::System,
            "injected message must have System role"
        );
        match &messages[0].content {
            Content::Text(text) => assert_eq!(text, TEST_BLOCK),
            other => panic!("expected Content::Text, got {other:?}"),
        }
        assert_eq!(
            messages[1].role,
            Role::User,
            "original user message must remain at index 1"
        );
    }

    /// When the first message is System with Parts content, insert a NEW system
    /// message at index 0 rather than mangling the structured parts.
    #[test]
    fn inject_inserts_new_system_when_first_message_is_parts_content() {
        let parts_message = Message {
            role: Role::System,
            content: Content::Parts(vec![ContentPart::Text {
                text: "structured system".to_string(),
            }]),
            reasoning_content: None,
        };
        let mut messages = vec![parts_message];
        let mode = inject_shared_context_block(&mut messages, TEST_BLOCK);
        assert_eq!(mode, "insert_new_system");
        assert_eq!(messages.len(), 2);
        // Index 0 is the newly inserted plain-text system message.
        assert_eq!(messages[0].role, Role::System);
        match &messages[0].content {
            Content::Text(text) => assert_eq!(text, TEST_BLOCK),
            other => panic!("expected Content::Text, got {other:?}"),
        }
        // Index 1 is the original Parts system message (unmodified).
        match &messages[1].content {
            Content::Parts(_) => {}
            other => panic!("original Parts message must be unchanged, got {other:?}"),
        }
    }

    /// When messages is empty, a new system message is inserted at index 0.
    #[test]
    fn inject_inserts_new_system_when_messages_vec_is_empty() {
        let mut messages: Vec<Message> = vec![];
        let mode = inject_shared_context_block(&mut messages, TEST_BLOCK);
        assert_eq!(mode, "insert_new_system");
        assert_eq!(messages.len(), 1);
        assert_eq!(messages[0].role, Role::System);
    }

    // -----------------------------------------------------------------------
    // PSL-1b: handler-level graceful degrade tests
    // -----------------------------------------------------------------------

    /// Fake surface service that returns errors for all read operations.
    struct AllErrorService;

    #[async_trait]
    impl PennySharedSurfaceService for AllErrorService {
        async fn recent_activity(
            &self,
            _actor: &gadgetron_core::knowledge::AuthenticatedContext,
            _limit: u32,
        ) -> gadgetron_core::error::Result<
            Vec<gadgetron_core::agent::shared_context::PennyActivityDigest>,
        > {
            Err(GadgetronError::Provider("activity down".into()))
        }
        async fn pending_candidates(
            &self,
            _actor: &gadgetron_core::knowledge::AuthenticatedContext,
            _limit: u32,
        ) -> gadgetron_core::error::Result<
            Vec<gadgetron_core::agent::shared_context::PennyCandidateDigest>,
        > {
            Err(GadgetronError::Provider("candidates down".into()))
        }
        async fn pending_approvals(
            &self,
            _actor: &gadgetron_core::knowledge::AuthenticatedContext,
            _limit: u32,
        ) -> gadgetron_core::error::Result<
            Vec<gadgetron_core::agent::shared_context::PennyApprovalDigest>,
        > {
            Err(GadgetronError::Provider("approvals down".into()))
        }
        async fn request_evidence(
            &self,
            _actor: &gadgetron_core::knowledge::AuthenticatedContext,
            _request_id: Uuid,
        ) -> gadgetron_core::error::Result<
            gadgetron_core::workbench::WorkbenchRequestEvidenceResponse,
        > {
            Err(GadgetronError::Forbidden)
        }
        async fn decide_candidate(
            &self,
            _actor: &gadgetron_core::knowledge::AuthenticatedContext,
            _request: gadgetron_core::agent::shared_context::PennyCandidateDecisionRequest,
        ) -> gadgetron_core::error::Result<
            gadgetron_core::agent::shared_context::PennyCandidateDecisionReceipt,
        > {
            Err(GadgetronError::Forbidden)
        }
    }

    fn make_state_with_psl_service(
        provider: impl LlmProvider + 'static,
        provider_name: &str,
        surface: Option<Arc<dyn PennySharedSurfaceService>>,
        agent_cfg: AgentConfig,
    ) -> AppState {
        let (audit_writer, _rx) = AuditWriter::new(TEST_AUDIT_CAPACITY);
        let mut providers: HashMap<String, Arc<dyn LlmProvider>> = HashMap::new();
        providers.insert(provider_name.to_string(), Arc::new(provider));

        let metrics = Arc::new(MetricsStore::new());
        let routing_config = gadgetron_core::routing::RoutingConfig {
            default_strategy: gadgetron_core::routing::RoutingStrategy::RoundRobin,
            fallbacks: HashMap::new(),
            costs: HashMap::new(),
        };
        let lrouter = LlmRouter::new(providers.clone(), routing_config, metrics);

        let providers_for_state: HashMap<String, Arc<dyn LlmProvider + Send + Sync>> = providers
            .into_iter()
            .map(|(k, v)| (k, v as Arc<dyn LlmProvider + Send + Sync>))
            .collect();

        // Build the penny_assembler from the surface if present.
        // Uses DefaultPennyTurnContextAssembler which requires a Sized S.
        // We use the Arc<dyn PennySharedSurfaceService> blanket impl.
        let penny_assembler: Option<Arc<dyn PennyTurnContextAssembler>> =
            surface.as_ref().map(|svc| {
                let assembler = DefaultPennyTurnContextAssembler {
                    service: Arc::new(svc.clone()),
                    config: agent_cfg.shared_context.clone(),
                };
                Arc::new(assembler) as Arc<dyn PennyTurnContextAssembler>
            });

        AppState {
            key_validator: Arc::new(AlwaysAcceptValidator::new(vec![Scope::OpenAiCompat])),
            quota_enforcer: Arc::new(InMemoryQuotaEnforcer),
            audit_writer: Arc::new(audit_writer),
            providers: Arc::new(providers_for_state),
            router: Some(Arc::new(lrouter)),
            pg_pool: Some(lazy_pool()),
            no_db: false,
            tui_tx: None,
            workbench: None,
            penny_shared_surface: surface,
            agent_config: Arc::new(agent_cfg),
            penny_assembler,
            activity_capture_store: None,
            candidate_coordinator: None,
        }
    }

    /// When `penny_shared_surface` is `None`, the request proceeds without any
    /// bootstrap injection — messages are unchanged.
    #[tokio::test]
    async fn inject_does_nothing_when_service_none() {
        let state = make_state_with_psl_service(
            FakeLlmProvider::new("fake-model"),
            "fake",
            None,
            AgentConfig::default(),
        );
        let app = build_test_app(state);

        let body_json = serde_json::to_vec(&chat_request_body(false)).unwrap();
        let req = Request::builder()
            .method("POST")
            .uri("/v1/chat/completions")
            .header("content-type", "application/json")
            .header("authorization", format!("Bearer {VALID_TOKEN}"))
            .body(Body::from(body_json))
            .unwrap();

        let resp = app.oneshot(req).await.unwrap();
        // Handler must return 200 normally — no bootstrap injection.
        assert_eq!(resp.status(), StatusCode::OK);
    }

    /// When `agent_config.shared_context.enabled = false`, no bootstrap is
    /// injected even if the service is configured.
    #[tokio::test]
    async fn inject_does_nothing_when_flag_disabled() {
        let mut cfg = AgentConfig::default();
        cfg.shared_context.enabled = false;

        let state = make_state_with_psl_service(
            FakeLlmProvider::new("fake-model"),
            "fake",
            Some(Arc::new(AllErrorService)),
            cfg,
        );
        let app = build_test_app(state);

        let body_json = serde_json::to_vec(&chat_request_body(false)).unwrap();
        let req = Request::builder()
            .method("POST")
            .uri("/v1/chat/completions")
            .header("content-type", "application/json")
            .header("authorization", format!("Bearer {VALID_TOKEN}"))
            .body(Body::from(body_json))
            .unwrap();

        let resp = app.oneshot(req).await.unwrap();
        // Must return 200 — AllErrorService never gets called.
        assert_eq!(resp.status(), StatusCode::OK);
    }

    /// When the assembler's service returns errors for all reads, the handler
    /// must still return 200 (graceful degrade — no 5xx caused by bootstrap failure).
    #[tokio::test]
    async fn inject_degrades_gracefully_when_assembler_errs() {
        // AllErrorService causes degraded bootstrap but assembler returns Ok(degraded).
        let state = make_state_with_psl_service(
            FakeLlmProvider::new("fake-model"),
            "fake",
            Some(Arc::new(AllErrorService)),
            AgentConfig::default(),
        );
        let app = build_test_app(state);

        let body_json = serde_json::to_vec(&chat_request_body(false)).unwrap();
        let req = Request::builder()
            .method("POST")
            .uri("/v1/chat/completions")
            .header("content-type", "application/json")
            .header("authorization", format!("Bearer {VALID_TOKEN}"))
            .body(Body::from(body_json))
            .unwrap();

        let resp = app.oneshot(req).await.unwrap();
        // Key invariant: bootstrap failure must NOT produce a 5xx response.
        let status = resp.status().as_u16();
        assert!(
            status < 500,
            "bootstrap service failure must not cause 5xx; got {status}"
        );
        assert_eq!(status, 200, "degraded bootstrap still produces 200 OK");
    }

    /// Calling the handler twice with the same conversation_id must invoke the
    /// assembler both times — session store does NOT short-circuit bootstrap
    /// (doc §2.2.4: "every turn gets a fresh bootstrap").
    #[tokio::test]
    async fn inject_reassembles_every_turn_even_with_conversation_id() {
        use std::sync::atomic::{AtomicUsize, Ordering};

        /// Service that counts how many times `recent_activity` was called.
        struct CountingService {
            call_count: Arc<AtomicUsize>,
        }

        #[async_trait]
        impl PennySharedSurfaceService for CountingService {
            async fn recent_activity(
                &self,
                _actor: &gadgetron_core::knowledge::AuthenticatedContext,
                _limit: u32,
            ) -> gadgetron_core::error::Result<
                Vec<gadgetron_core::agent::shared_context::PennyActivityDigest>,
            > {
                self.call_count.fetch_add(1, Ordering::Relaxed);
                Ok(vec![])
            }
            async fn pending_candidates(
                &self,
                _actor: &gadgetron_core::knowledge::AuthenticatedContext,
                _limit: u32,
            ) -> gadgetron_core::error::Result<
                Vec<gadgetron_core::agent::shared_context::PennyCandidateDigest>,
            > {
                Ok(vec![])
            }
            async fn pending_approvals(
                &self,
                _actor: &gadgetron_core::knowledge::AuthenticatedContext,
                _limit: u32,
            ) -> gadgetron_core::error::Result<
                Vec<gadgetron_core::agent::shared_context::PennyApprovalDigest>,
            > {
                Ok(vec![])
            }
            async fn request_evidence(
                &self,
                _actor: &gadgetron_core::knowledge::AuthenticatedContext,
                _request_id: Uuid,
            ) -> gadgetron_core::error::Result<
                gadgetron_core::workbench::WorkbenchRequestEvidenceResponse,
            > {
                Err(GadgetronError::Forbidden)
            }
            async fn decide_candidate(
                &self,
                _actor: &gadgetron_core::knowledge::AuthenticatedContext,
                _request: gadgetron_core::agent::shared_context::PennyCandidateDecisionRequest,
            ) -> gadgetron_core::error::Result<
                gadgetron_core::agent::shared_context::PennyCandidateDecisionReceipt,
            > {
                Err(GadgetronError::Forbidden)
            }
        }

        let call_count = Arc::new(AtomicUsize::new(0));
        let service = Arc::new(CountingService {
            call_count: call_count.clone(),
        });

        let state = make_state_with_psl_service(
            FakeLlmProvider::new("fake-model"),
            "fake",
            Some(service as Arc<dyn PennySharedSurfaceService>),
            AgentConfig::default(),
        );
        let app = build_test_app(state);

        // Use a fixed conversation_id in both requests.
        let body_json = serde_json::to_vec(&serde_json::json!({
            "model": "fake-model",
            "messages": [{"role": "user", "content": "hi"}],
            "stream": false,
            "conversation_id": "conv-resume-test"
        }))
        .unwrap();

        // First request.
        let req1 = Request::builder()
            .method("POST")
            .uri("/v1/chat/completions")
            .header("content-type", "application/json")
            .header("authorization", format!("Bearer {VALID_TOKEN}"))
            .body(Body::from(body_json.clone()))
            .unwrap();
        let resp1 = app.clone().oneshot(req1).await.unwrap();
        assert_eq!(resp1.status(), StatusCode::OK);

        // Second request with the same conversation_id.
        let req2 = Request::builder()
            .method("POST")
            .uri("/v1/chat/completions")
            .header("content-type", "application/json")
            .header("authorization", format!("Bearer {VALID_TOKEN}"))
            .body(Body::from(body_json))
            .unwrap();
        let resp2 = app.oneshot(req2).await.unwrap();
        assert_eq!(resp2.status(), StatusCode::OK);

        // Assembler must have been called twice (once per turn).
        let count = call_count.load(Ordering::Relaxed);
        assert_eq!(
            count, 2,
            "assembler must be invoked on every turn regardless of conversation_id; got {count}"
        );
    }
}
