"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import { AssistantRuntimeProvider } from "@assistant-ui/react";
import { useChatRuntime } from "@assistant-ui/react-ai-sdk";
import { OpenAIChatTransport } from "../openai-transport";
import { WorkbenchShell } from "../components/shell/workbench-shell";
import { AuthProvider, useAuth } from "../lib/auth-context";
import { EvidenceProvider } from "../lib/evidence-context";
import { WorkbenchSubjectProvider } from "../lib/workbench-subject-context";
import {
  getActiveConversationId,
  setActiveConversationId,
} from "../lib/conversation-id";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Card, CardContent } from "../components/ui/card";

// ---------------------------------------------------------------------------
// /web post-auth shell — Next.js Route Group `(shell)` layout.
//
// All routes under `(shell)/` (chat at `/`, `/wiki`, `/dashboard`) share
// this layout. The layout mounts:
//   1. <AuthProvider>   — one source of truth for the pasted API key
//   2. <WorkbenchShell> — shared chrome (StatusStrip / LeftRail / EvidencePane)
//   3. <AssistantRuntimeProvider> — chat runtime hoisted here so the
//      chat thread survives navigation to /wiki or /dashboard (ROADMAP
//      ISSUE 29 TASK 29.2 — was previously inside page.tsx which
//      unmounted on route change, resetting in-flight responses).
//
// Route Group `(shell)` does not affect the URL — visitors still browse
// `/web`, `/web/wiki`, `/web/dashboard`. It only scopes this layout so
// future non-shell routes (e.g. a stripped-down `/debug` page) can opt
// out by living outside the group.
// ---------------------------------------------------------------------------

function getApiBase(): string {
  if (typeof document === "undefined") return "/v1";
  const meta = document.querySelector<HTMLMetaElement>(
    'meta[name="gadgetron-api-base"]',
  );
  return meta?.content || "/v1";
}

function LoginCard() {
  const { saveKey } = useAuth();
  const [keyInput, setKeyInput] = useState("");
  const submit = () => {
    const k = keyInput.trim();
    if (k) {
      saveKey(k);
      setKeyInput("");
    }
  };
  return (
    <div
      className="flex flex-1 items-center justify-center p-6"
      data-testid="auth-gate"
    >
      <Card className="w-full max-w-md border-zinc-800 bg-zinc-900">
        <CardContent className="flex flex-col gap-4 p-6">
          <div>
            <h2 className="text-sm font-semibold text-zinc-200">
              Authentication required
            </h2>
            <p className="mt-1 text-xs text-zinc-500">
              Enter the API key generated by{" "}
              <code className="rounded bg-zinc-800 px-1 py-0.5 font-mono text-[11px] text-zinc-400">
                gadgetron key create
              </code>
              . Stored in localStorage.
            </p>
          </div>
          <Input
            type="password"
            value={keyInput}
            onChange={(e) => setKeyInput(e.target.value)}
            placeholder="gad_live_..."
            onKeyDown={(e) => e.key === "Enter" && submit()}
            className="border-zinc-700 bg-zinc-800 font-mono text-xs text-zinc-200 placeholder:text-zinc-600"
          />
          <Button onClick={submit} className="w-full">
            Sign in
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}

function AuthedShell({ children }: { children: ReactNode }) {
  // Transport sends Bearer when an API key exists, falls back to the
  // session cookie otherwise. Same-origin cookies are sent by default.
  const transport = useMemo(
    () =>
      new OpenAIChatTransport({
        api: `${getApiBase()}/chat/completions`,
        model: "penny",
        headers: (): Record<string, string> => {
          const h: Record<string, string> = {};
          if (typeof localStorage !== "undefined") {
            const key = localStorage.getItem("gadgetron_api_key");
            if (key) h["Authorization"] = `Bearer ${key}`;
            // Per-tab active conversation. The id lives in
            // `sessionStorage` so two parallel browser windows don't
            // stomp on each other's chat state. Helper handles the
            // localStorage→sessionStorage migration on first read.
            let convId = getActiveConversationId();
            if (!convId) {
              // Fresh tab with no inherited id: mint one so the very
              // first turn lands in a row and the sidebar picks it up.
              convId = crypto.randomUUID?.() ?? null;
              if (convId) setActiveConversationId(convId);
            }
            if (convId) h["X-Gadgetron-Conversation-Id"] = convId;
          }
          return h;
        },
      }),
    [],
  );
  const runtime = useChatRuntime({ transport });

  return (
    <EvidenceProvider>
      <WorkbenchSubjectProvider>
        <AssistantRuntimeProvider runtime={runtime}>
          <WorkbenchShell>{children}</WorkbenchShell>
        </AssistantRuntimeProvider>
      </WorkbenchSubjectProvider>
    </EvidenceProvider>
  );
}

/// Auth state we care about for the shell gate: either an API key
/// (pre-OAuth flow) or a live session cookie validates.
type SessionCheck = "checking" | "valid" | "none";

function useSessionCheck(hasApiKey: boolean): SessionCheck {
  const [state, setState] = useState<SessionCheck>(
    hasApiKey ? "valid" : "checking",
  );
  useEffect(() => {
    if (hasApiKey) {
      setState("valid");
      return;
    }
    let cancelled = false;
    (async () => {
      try {
        const base =
          (typeof document !== "undefined" &&
            document
              .querySelector<HTMLMetaElement>(
                'meta[name="gadgetron-api-base"]',
              )
              ?.content) ||
          "/v1";
        const root = base.replace(/\/v\d+$/, "");
        const res = await fetch(`${root}/api/v1/auth/whoami`, {
          credentials: "include",
        });
        if (!cancelled) setState(res.ok ? "valid" : "none");
      } catch {
        if (!cancelled) setState("none");
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [hasApiKey]);
  return state;
}

function ShellSwitch({ children }: { children: ReactNode }) {
  const { apiKey, hydrated } = useAuth();
  const sessionState = useSessionCheck(!!apiKey);

  useEffect(() => {
    // Once we've definitively determined no auth, hard-redirect to the
    // login page. Client-side `router.push` would keep the shell
    // mounted briefly and double-run effects.
    if (
      hydrated &&
      !apiKey &&
      sessionState === "none" &&
      typeof window !== "undefined" &&
      !window.location.pathname.startsWith("/web/login")
    ) {
      window.location.assign("/web/login");
    }
  }, [hydrated, apiKey, sessionState]);

  // Before the initial localStorage read or the whoami probe completes,
  // render the shell chrome with a blank body. This avoids a one-frame
  // flash of the login form on an authed reload.
  if (!hydrated || sessionState === "checking") {
    return <WorkbenchShell preAuth>{null}</WorkbenchShell>;
  }

  if (!apiKey && sessionState === "none") {
    // Redirect in-flight — render nothing to avoid a flash.
    return <WorkbenchShell preAuth>{null}</WorkbenchShell>;
  }

  return <AuthedShell>{children}</AuthedShell>;
}

// LoginCard kept in the module in case other callers import it, but the
// shell no longer mounts it — the dedicated /web/login page owns the
// sign-in UI so Google OAuth + password login can share one screen.
void LoginCard;

export default function ShellLayout({ children }: { children: ReactNode }) {
  return (
    <AuthProvider>
      <ShellSwitch>{children}</ShellSwitch>
    </AuthProvider>
  );
}
