"use client";

import { useMemo, useState, type ReactNode } from "react";
import { AssistantRuntimeProvider } from "@assistant-ui/react";
import { useChatRuntime } from "@assistant-ui/react-ai-sdk";
import { OpenAIChatTransport } from "../openai-transport";
import { WorkbenchShell } from "../components/shell/workbench-shell";
import { AuthProvider, useAuth } from "../lib/auth-context";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Card, CardContent } from "../components/ui/card";

// ---------------------------------------------------------------------------
// /web post-auth shell — Next.js Route Group `(shell)` layout.
//
// All routes under `(shell)/` (chat at `/`, `/wiki`, `/dashboard`) share
// this layout. The layout mounts:
//   1. <AuthProvider>   — one source of truth for the pasted API key
//   2. <WorkbenchShell> — shared chrome (StatusStrip / LeftRail / EvidencePane)
//   3. <AssistantRuntimeProvider> — chat runtime hoisted here so the
//      chat thread survives navigation to /wiki or /dashboard (ROADMAP
//      ISSUE 29 TASK 29.2 — was previously inside page.tsx which
//      unmounted on route change, resetting in-flight responses).
//
// Route Group `(shell)` does not affect the URL — visitors still browse
// `/web`, `/web/wiki`, `/web/dashboard`. It only scopes this layout so
// future non-shell routes (e.g. a stripped-down `/debug` page) can opt
// out by living outside the group.
// ---------------------------------------------------------------------------

function getApiBase(): string {
  if (typeof document === "undefined") return "/v1";
  const meta = document.querySelector<HTMLMetaElement>(
    'meta[name="gadgetron-api-base"]',
  );
  return meta?.content || "/v1";
}

function LoginCard() {
  const { saveKey } = useAuth();
  const [keyInput, setKeyInput] = useState("");
  const submit = () => {
    const k = keyInput.trim();
    if (k) {
      saveKey(k);
      setKeyInput("");
    }
  };
  return (
    <div
      className="flex flex-1 items-center justify-center p-6"
      data-testid="auth-gate"
    >
      <Card className="w-full max-w-md border-zinc-800 bg-zinc-900">
        <CardContent className="flex flex-col gap-4 p-6">
          <div>
            <h2 className="text-sm font-semibold text-zinc-200">
              Authentication required
            </h2>
            <p className="mt-1 text-xs text-zinc-500">
              Enter the API key generated by{" "}
              <code className="rounded bg-zinc-800 px-1 py-0.5 font-mono text-[11px] text-zinc-400">
                gadgetron key create
              </code>
              . Stored in localStorage.
            </p>
          </div>
          <Input
            type="password"
            value={keyInput}
            onChange={(e) => setKeyInput(e.target.value)}
            placeholder="gad_live_..."
            onKeyDown={(e) => e.key === "Enter" && submit()}
            className="border-zinc-700 bg-zinc-800 font-mono text-xs text-zinc-200 placeholder:text-zinc-600"
          />
          <Button onClick={submit} className="w-full">
            Sign in
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}

function AuthedShell({ children }: { children: ReactNode }) {
  const { apiKey } = useAuth();

  // `useChatRuntime` depends on a stable transport instance. The
  // transport reads the API key lazily from `localStorage` on each
  // request, so we don't need to rebuild it when `apiKey` changes
  // within a session; rebuilding would remount the runtime and defeat
  // the whole point of hoisting it. `apiKey` is in the dep array only
  // so the transport closure captures the latest header function.
  const transport = useMemo(
    () =>
      new OpenAIChatTransport({
        api: `${getApiBase()}/chat/completions`,
        model: "penny",
        headers: (): Record<string, string> => {
          const key =
            typeof localStorage !== "undefined"
              ? localStorage.getItem("gadgetron_api_key")
              : null;
          return key ? { Authorization: `Bearer ${key}` } : {};
        },
      }),
    [],
  );
  const runtime = useChatRuntime({ transport });

  // `apiKey` guarantees we are post-auth, but narrow for TypeScript.
  if (!apiKey) return null;

  return (
    <AssistantRuntimeProvider runtime={runtime}>
      <WorkbenchShell>{children}</WorkbenchShell>
    </AssistantRuntimeProvider>
  );
}

function ShellSwitch({ children }: { children: ReactNode }) {
  const { apiKey, hydrated } = useAuth();

  // Before the initial localStorage read completes, render the shell
  // chrome with a blank body. This avoids a one-frame flash of the
  // login form on an authed reload.
  if (!hydrated) {
    return <WorkbenchShell preAuth>{null}</WorkbenchShell>;
  }

  if (!apiKey) {
    return (
      <WorkbenchShell preAuth>
        <LoginCard />
      </WorkbenchShell>
    );
  }

  return <AuthedShell>{children}</AuthedShell>;
}

export default function ShellLayout({ children }: { children: ReactNode }) {
  return (
    <AuthProvider>
      <ShellSwitch>{children}</ShellSwitch>
    </AuthProvider>
  );
}
