-- ISSUE 3 (production safety) TASK 3.2: persistent audit table for
-- workbench direct-action dispatches.
--
-- Emitted from `gadgetron-gateway::web::action_service::invoke` step 6
-- (pending_approval) and step 8/9 (ok / error) via the
-- `ActionAuditSink` trait defined in `gadgetron-core::audit::action`.
--
-- The `event_id` is generated by the action service so the HTTP
-- response can carry it as `WorkbenchActionResult.audit_event_id`
-- and a caller can GET this row later for attestation. We use the
-- event_id as the primary key (UUID, not bigserial) so the
-- client-facing id IS the persistent id — no mapping layer.

CREATE TABLE action_audit_events (
    event_id       UUID PRIMARY KEY,
    -- Workbench catalog entry id (e.g. "wiki-write").
    action_id      TEXT NOT NULL,
    -- Dispatched gadget name (e.g. "wiki.write"), or NULL when the
    -- action has `gadget_name: None` (synthetic result path).
    gadget_name    TEXT NULL,
    -- Acting principal + tenant. TEXT (UUID cast at write time) to
    -- match the tool_audit_events convention.
    actor_user_id  TEXT NOT NULL,
    tenant_id      TEXT NOT NULL,
    -- Outcome: success | error | pending_approval.
    outcome        TEXT NOT NULL CHECK (outcome IN ('success', 'error', 'pending_approval')),
    -- Short-form GadgetError::error_code() when outcome='error'.
    error_code     TEXT NULL,
    elapsed_ms     BIGINT NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Time-range scans for recent activity + per-tenant timeline.
CREATE INDEX action_audit_events_created_at_idx
    ON action_audit_events (created_at DESC);
CREATE INDEX action_audit_events_tenant_created_idx
    ON action_audit_events (tenant_id, created_at DESC);
-- `/api/v1/audit/events?action_id=...` query path (TASK 3.4).
CREATE INDEX action_audit_events_action_id_idx
    ON action_audit_events (action_id);
